version: '2'

services:
  anyway:
    build: .
    image: hasadna/anyway:latest
    ports:
      - "8080:5000"
    environment:
      - DATABASE_URL=sqlite:////anyway/local.db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
    volumes:
      - ./static:/anyway/static
    restart: always
    depends_on:
      - rabbitmq

  anyway_celery:
    build: .
    image: hasadna/anyway:latest
    environment:
      - DATABASE_URL=postgresql://anyway:anyway@db/anyway
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq
    restart: always
    entrypoint: ''
    command: celery worker -A anyway.clusters_calculator
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq
