version: '3'

x-redash-service:
  &redash-service
  image: redash/redash:8.0.0.b32245
  depends_on:
    - postgres
    - redis
  env_file: ./.env
  restart: always

services:
  redis:
    container_name: redash-redis
    image: redis:5.0-alpine
    restart: always

  postgres:
    container_name: redash-db
    image: postgres:9.6-alpine
    env_file: ./.env
    volumes:
      - redash-postgres-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGPORT=5433 # The default port (5432) is reserved for the db of anyway 
    ports:
      - "5433:5433"
    expose:
      - "5433"

  redash-server:
    <<: *redash-service
    container_name: redash-server
    command: server
    environment:
      REDASH_WEB_WORKERS: 4
    ports:
      - "5001:5000"
    expose:
      - "5001"

  scheduler:
    <<: *redash-service
    container_name: redash-scheduler
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1

  scheduled_worker:
    <<: *redash-service
    container_name: redash-scheduled-worker
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1

  adhoc_worker:
    <<: *redash-service
    container_name: redash-adhoc-worker
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2

volumes:
  redash-postgres-data:
