from sqlalchemy import and_, select
from anyway.models import (
    AccidentMarker,
    Involved,
    InvolvedView,
    Vehicle,
    ColumnsDescription,
    PoliceUnit,
    RoadType,
    AccidentSeverity,
    AccidentType,
    RoadShape,
    OneLane,
    MultiLane,
    SpeedLimit,
    RoadIntactness,
    RoadWidth,
    RoadSign,
    RoadLight,
    RoadControl,
    VehiclesView,
    Weather,
    RoadSurface,
    RoadObjecte,
    ObjectDistance,
    DidntCross,
    CrossMode,
    CrossLocation,
    CrossDirection,
    DrivingDirections,
    VehicleStatus,
    InvolvedType,
    SafetyMeasures,
    InjurySeverity,
    DayType,
    DayNight,
    DayInWeek,
    TrafficLight,
    VehicleAttribution,
    VehicleType,
    InjuredType,
    InjuredPosition,
    AccidentMonth,
    PopulationType,
    Sex,
    GeoArea,
    Region,
    MunicipalStatus,
    District,
    NaturalArea,
    YishuvShape,
    AgeGroup,
    AccidentHourRaw,
    EngineVolume,
    TotalWeight,
    HospitalTime,
    MedicalType,
    ReleaseDest,
    SafetyMeasuresUse,
    LateDeceased,
    LocationAccuracy,
    ProviderCode,
    VehicleDamage,
    Streets,
    RoadSegments,
    AccidentMarkerView
)


class Views(object):
    def create_markers_hebrew_view(self):
        selected_columns = [
            AccidentMarker.id,
            AccidentMarker.provider_and_id,
            AccidentMarker.provider_code,
            ProviderCode.provider_code_hebrew,
            AccidentMarker.file_type_police,
            AccidentMarker.accident_type,
            AccidentType.accident_type_hebrew,
            AccidentMarker.accident_severity,
            AccidentSeverity.accident_severity_hebrew,
            AccidentMarker.created.label('accident_timestamp'),
            AccidentMarker.location_accuracy,
            LocationAccuracy.location_accuracy_hebrew,
            AccidentMarker.road_type,
            RoadType.road_type_hebrew,
            AccidentMarker.road_shape,
            RoadShape.road_shape_hebrew,
            AccidentMarker.day_type,
            DayType.day_type_hebrew,
            AccidentMarker.police_unit,
            PoliceUnit.police_unit_hebrew,
            AccidentMarker.one_lane,
            OneLane.one_lane_hebrew,
            AccidentMarker.multi_lane,
            MultiLane.multi_lane_hebrew,
            AccidentMarker.speed_limit,
            SpeedLimit.speed_limit_hebrew,
            AccidentMarker.road_intactness,
            RoadIntactness.road_intactness_hebrew,
            AccidentMarker.road_width,
            RoadWidth.road_width_hebrew,
            AccidentMarker.road_sign,
            RoadSign.road_sign_hebrew,
            AccidentMarker.road_light,
            RoadLight.road_light_hebrew,
            AccidentMarker.road_control,
            RoadControl.road_control_hebrew,
            AccidentMarker.weather,
            Weather.weather_hebrew,
            AccidentMarker.road_surface,
            RoadSurface.road_surface_hebrew,
            AccidentMarker.road_object,
            RoadObjecte.road_object_hebrew,
            AccidentMarker.object_distance,
            ObjectDistance.object_distance_hebrew,
            AccidentMarker.didnt_cross,
            DidntCross.didnt_cross_hebrew,
            AccidentMarker.cross_mode,
            CrossMode.cross_mode_hebrew,
            AccidentMarker.cross_location,
            CrossLocation.cross_location_hebrew,
            AccidentMarker.cross_direction,
            CrossDirection.cross_direction_hebrew,
            AccidentMarker.road1,
            AccidentMarker.road2,
            AccidentMarker.km,
            AccidentMarker.km_raw,
            AccidentMarker.km_accurate,
            RoadSegments.segment_id.label('road_segment_id'),
            RoadSegments.segment.label('road_segment_number'),
            (RoadSegments.from_name + " - " + RoadSegments.to_name).label('road_segment_name'),
            RoadSegments.from_km.label('road_segment_from_km'),
            RoadSegments.to_km.label('road_segment_to_km'),
            (RoadSegments.to_km - RoadSegments.from_km).label('road_segment_length_km'),
            AccidentMarker.yishuv_symbol,
            AccidentMarker.yishuv_name,
            AccidentMarker.geo_area,
            GeoArea.geo_area_hebrew,
            AccidentMarker.day_night,
            DayNight.day_night_hebrew,
            AccidentMarker.day_in_week,
            DayInWeek.day_in_week_hebrew,
            AccidentMarker.traffic_light,
            TrafficLight.traffic_light_hebrew,
            AccidentMarker.region,
            Region.region_hebrew,
            AccidentMarker.district,
            District.district_hebrew,
            AccidentMarker.natural_area,
            NaturalArea.natural_area_hebrew,
            AccidentMarker.municipal_status,
            MunicipalStatus.municipal_status_hebrew,
            AccidentMarker.yishuv_shape,
            YishuvShape.yishuv_shape_hebrew,
            AccidentMarker.street1,
            AccidentMarker.street1_hebrew,
            AccidentMarker.street2,
            AccidentMarker.street2_hebrew,
            AccidentMarker.house_number,
            AccidentMarker.non_urban_intersection,
            AccidentMarker.non_urban_intersection_hebrew,
            AccidentMarker.non_urban_intersection_by_junction_number,
            AccidentMarker.urban_intersection,
            AccidentMarker.accident_year,
            AccidentMarker.accident_month,
            AccidentMarker.accident_day,
            AccidentMarker.accident_hour_raw,
            AccidentHourRaw.accident_hour_raw_hebrew,
            AccidentMarker.accident_hour,
            AccidentMarker.accident_minute,
            AccidentMarker.geom,
            AccidentMarker.longitude,
            AccidentMarker.latitude,
            AccidentMarker.x,
            AccidentMarker.y
        ]

        table = AccidentMarker.__table__
        from_clause = table \
            .join(RoadSegments,
                  and_(AccidentMarker.road1 == RoadSegments.road,
                       RoadSegments.from_km <= AccidentMarker.km / 10,
                       AccidentMarker.km / 10 < RoadSegments.to_km),
                  isouter=True) \
            .join(AccidentType,
                  and_(AccidentMarker.accident_type == AccidentType.id,
                       AccidentMarker.accident_year == AccidentType.year,
                       AccidentMarker.provider_code == AccidentType.provider_code),
                  isouter=True) \
            .join(AccidentSeverity,
                  and_(AccidentMarker.accident_severity == AccidentSeverity.id,
                       AccidentMarker.accident_year == AccidentSeverity.year,
                       AccidentMarker.provider_code == AccidentSeverity.provider_code),
                  isouter=True) \
            .join(LocationAccuracy,
                  and_(AccidentMarker.location_accuracy == LocationAccuracy.id,
                       AccidentMarker.accident_year == LocationAccuracy.year,
                       AccidentMarker.provider_code == LocationAccuracy.provider_code),
                  isouter=True) \
            .join(RoadType,
                  and_(AccidentMarker.road_type == RoadType.id,
                       AccidentMarker.accident_year == RoadType.year,
                       AccidentMarker.provider_code == RoadType.provider_code),
                  isouter=True) \
            .join(RoadShape,
                  and_(AccidentMarker.road_shape == RoadShape.id,
                       AccidentMarker.accident_year == RoadShape.year,
                       AccidentMarker.provider_code == RoadShape.provider_code),
                  isouter=True) \
            .join(DayType,
                  and_(AccidentMarker.day_type == DayType.id,
                       AccidentMarker.accident_year == DayType.year,
                       AccidentMarker.provider_code == DayType.provider_code),
                  isouter=True) \
            .join(PoliceUnit,
                  and_(AccidentMarker.police_unit == PoliceUnit.id,
                       AccidentMarker.accident_year == PoliceUnit.year,
                       AccidentMarker.provider_code == PoliceUnit.provider_code),
                  isouter=True) \
            .join(OneLane,
                  and_(AccidentMarker.one_lane == OneLane.id,
                       AccidentMarker.accident_year == OneLane.year,
                       AccidentMarker.provider_code == OneLane.provider_code),
                  isouter=True) \
            .join(MultiLane,
                  and_(AccidentMarker.multi_lane == MultiLane.id,
                       AccidentMarker.accident_year == MultiLane.year,
                       AccidentMarker.provider_code == MultiLane.provider_code),
                  isouter=True) \
            .join(SpeedLimit,
                  and_(AccidentMarker.speed_limit == SpeedLimit.id,
                       AccidentMarker.accident_year == SpeedLimit.year,
                       AccidentMarker.provider_code == SpeedLimit.provider_code),
                  isouter=True) \
            .join(RoadIntactness,
                  and_(AccidentMarker.road_intactness == RoadIntactness.id,
                       AccidentMarker.accident_year == RoadIntactness.year,
                       AccidentMarker.provider_code == RoadIntactness.provider_code),
                  isouter=True) \
            .join(RoadWidth,
                  and_(AccidentMarker.road_width == RoadWidth.id,
                       AccidentMarker.accident_year == RoadWidth.year,
                       AccidentMarker.provider_code == RoadWidth.provider_code),
                  isouter=True) \
            .join(RoadSign,
                  and_(AccidentMarker.road_sign == RoadSign.id,
                       AccidentMarker.accident_year == RoadSign.year,
                       AccidentMarker.provider_code == RoadSign.provider_code),
                  isouter=True) \
            .join(RoadLight,
                  and_(AccidentMarker.road_light == RoadLight.id,
                       AccidentMarker.accident_year == RoadLight.year,
                       AccidentMarker.provider_code == RoadLight.provider_code),
                  isouter=True) \
            .join(RoadControl,
                  and_(AccidentMarker.road_control == RoadControl.id,
                       AccidentMarker.accident_year == RoadControl.year,
                       AccidentMarker.provider_code == RoadControl.provider_code),
                  isouter=True) \
            .join(Weather,
                  and_(AccidentMarker.weather == Weather.id,
                       AccidentMarker.accident_year == Weather.year,
                       AccidentMarker.provider_code == Weather.provider_code),
                  isouter=True) \
            .join(RoadSurface,
                  and_(AccidentMarker.road_surface == RoadSurface.id,
                       AccidentMarker.accident_year == RoadSurface.year,
                       AccidentMarker.provider_code == RoadSurface.provider_code),
                  isouter=True) \
            .join(RoadObjecte,
                  and_(AccidentMarker.road_object == RoadObjecte.id,
                       AccidentMarker.accident_year == RoadObjecte.year,
                       AccidentMarker.provider_code == RoadObjecte.provider_code),
                  isouter=True) \
            .join(ObjectDistance,
                  and_(AccidentMarker.object_distance == ObjectDistance.id,
                       AccidentMarker.accident_year == ObjectDistance.year,
                       AccidentMarker.provider_code == ObjectDistance.provider_code),
                  isouter=True) \
            .join(DidntCross,
                  and_(AccidentMarker.didnt_cross == DidntCross.id,
                       AccidentMarker.accident_year == DidntCross.year,
                       AccidentMarker.provider_code == DidntCross.provider_code),
                  isouter=True) \
            .join(CrossMode,
                  and_(AccidentMarker.cross_mode == CrossMode.id,
                       AccidentMarker.accident_year == CrossMode.year,
                       AccidentMarker.provider_code == CrossMode.provider_code),
                  isouter=True) \
            .join(CrossLocation,
                  and_(AccidentMarker.cross_location == CrossLocation.id,
                       AccidentMarker.accident_year == CrossLocation.year,
                       AccidentMarker.provider_code == CrossLocation.provider_code),
                  isouter=True) \
            .join(CrossDirection,
                  and_(AccidentMarker.cross_direction == CrossDirection.id,
                       AccidentMarker.accident_year == CrossDirection.year,
                       AccidentMarker.provider_code == CrossDirection.provider_code),
                  isouter=True) \
            .join(GeoArea,
                  and_(AccidentMarker.geo_area == GeoArea.id,
                       AccidentMarker.accident_year == GeoArea.year,
                       AccidentMarker.provider_code == GeoArea.provider_code),
                  isouter=True) \
            .join(DayNight,
                  and_(AccidentMarker.day_night == DayNight.id,
                       AccidentMarker.accident_year == DayNight.year,
                       AccidentMarker.provider_code == DayNight.provider_code),
                  isouter=True) \
            .join(DayInWeek,
                  and_(AccidentMarker.day_in_week == DayInWeek.id,
                       AccidentMarker.accident_year == DayInWeek.year,
                       AccidentMarker.provider_code == DayInWeek.provider_code),
                  isouter=True) \
            .join(TrafficLight,
                  and_(AccidentMarker.traffic_light == TrafficLight.id,
                       AccidentMarker.accident_year == TrafficLight.year,
                       AccidentMarker.provider_code == TrafficLight.provider_code),
                  isouter=True) \
            .join(Region,
                  and_(AccidentMarker.region == Region.id,
                       AccidentMarker.accident_year == Region.year,
                       AccidentMarker.provider_code == Region.provider_code),
                  isouter=True) \
            .join(District,
                  and_(AccidentMarker.district == District.id,
                       AccidentMarker.accident_year == District.year,
                       AccidentMarker.provider_code == District.provider_code),
                  isouter=True) \
            .join(NaturalArea,
                  and_(AccidentMarker.natural_area == NaturalArea.id,
                       AccidentMarker.accident_year == NaturalArea.year,
                       AccidentMarker.provider_code == NaturalArea.provider_code),
                  isouter=True) \
            .join(MunicipalStatus,
                  and_(AccidentMarker.municipal_status == MunicipalStatus.id,
                       AccidentMarker.accident_year == MunicipalStatus.year,
                       AccidentMarker.provider_code == MunicipalStatus.provider_code),
                  isouter=True) \
            .join(YishuvShape,
                  and_(AccidentMarker.yishuv_shape == YishuvShape.id,
                       AccidentMarker.accident_year == YishuvShape.year,
                       AccidentMarker.provider_code == YishuvShape.provider_code),
                  isouter=True) \
            .join(AccidentHourRaw,
                  and_(AccidentMarker.accident_hour_raw == AccidentHourRaw.id,
                       AccidentMarker.accident_year == AccidentHourRaw.year,
                       AccidentMarker.provider_code == AccidentHourRaw.provider_code),
                  isouter=True) \
            .join(ProviderCode,
                  and_(AccidentMarker.provider_code == ProviderCode.id),
                  isouter=True)
        return select(selected_columns) \
            .select_from(from_clause)

    def create_involved_hebrew_view(self):
        selected_columns = [
            Involved.accident_id,
            Involved.provider_and_id,
            Involved.provider_code,
            Involved.file_type_police,
            Involved.involved_type,
            InvolvedType.involved_type_hebrew,
            Involved.license_acquiring_date,
            Involved.age_group,
            AgeGroup.age_group_hebrew,
            Involved.sex,
            Sex.sex_hebrew,
            Involved.vehicle_type,
            VehicleType.vehicle_type_hebrew,
            Involved.safety_measures,
            SafetyMeasures.safety_measures_hebrew,
            Involved.involve_yishuv_symbol,
            Involved.involve_yishuv_name,
            Involved.injury_severity,
            InjurySeverity.injury_severity_hebrew,
            Involved.injured_type,
            InjuredType.injured_type_hebrew,
            Involved.injured_position,
            InjuredPosition.injured_position_hebrew,
            Involved.population_type,
            PopulationType.population_type_hebrew,
            Involved.home_region,
            Region.region_hebrew.label("home_region_hebrew"),
            Involved.home_district,
            District.district_hebrew.label("home_district_hebrew"),
            Involved.home_natural_area,
            NaturalArea.natural_area_hebrew.label("home_natural_area_hebrew"),
            Involved.home_municipal_status,
            MunicipalStatus.municipal_status_hebrew.label("home_municipal_status_hebrew"),
            Involved.home_yishuv_shape,
            YishuvShape.yishuv_shape_hebrew.label("home_yishuv_shape_hebrew"),
            Involved.hospital_time,
            HospitalTime.hospital_time_hebrew,
            Involved.medical_type,
            MedicalType.medical_type_hebrew,
            Involved.release_dest,
            ReleaseDest.release_dest_hebrew,
            Involved.safety_measures_use,
            SafetyMeasuresUse.safety_measures_use_hebrew,
            Involved.late_deceased,
            LateDeceased.late_deceased_hebrew,
            Involved.car_id,
            Involved.involve_id,
            Involved.accident_year,
            Involved.accident_month
        ]
        table = Involved.__table__
        from_clause = table \
            .join(InvolvedType,
                  and_(Involved.involved_type == InvolvedType.id,
                       Involved.accident_year == InvolvedType.year,
                       Involved.provider_code == InvolvedType.provider_code),
                  isouter=True) \
            .join(AgeGroup,
                  and_(Involved.age_group == AgeGroup.id,
                       Involved.accident_year == AgeGroup.year,
                       Involved.provider_code == AgeGroup.provider_code),
                  isouter=True) \
            .join(Sex,
                  and_(Involved.sex == Sex.id,
                       Involved.accident_year == Sex.year,
                       Involved.provider_code == Sex.provider_code),
                  isouter=True) \
            .join(VehicleType,
                  and_(Involved.vehicle_type == VehicleType.id,
                       Involved.accident_year == VehicleType.year,
                       Involved.provider_code == VehicleType.provider_code),
                  isouter=True) \
            .join(SafetyMeasures,
                  and_(Involved.safety_measures == SafetyMeasures.id,
                       Involved.accident_year == SafetyMeasures.year,
                       Involved.provider_code == SafetyMeasures.provider_code),
                  isouter=True) \
            .join(InjurySeverity,
                  and_(Involved.injury_severity == InjurySeverity.id,
                       Involved.accident_year == InjurySeverity.year,
                       Involved.provider_code == InjurySeverity.provider_code),
                  isouter=True) \
            .join(InjuredType,
                  and_(Involved.injured_type == InjuredType.id,
                       Involved.accident_year == InjuredType.year,
                       Involved.provider_code == InjuredType.provider_code),
                  isouter=True) \
            .join(InjuredPosition,
                  and_(Involved.injured_position == InjuredPosition.id,
                       Involved.accident_year == InjuredPosition.year,
                       Involved.provider_code == InjuredPosition.provider_code),
                  isouter=True) \
            .join(PopulationType,
                  and_(Involved.population_type == PopulationType.id,
                       Involved.accident_year == PopulationType.year,
                       Involved.provider_code == PopulationType.provider_code),
                  isouter=True) \
            .join(Region,
                  and_(Involved.home_region == Region.id,
                       Involved.accident_year == Region.year,
                       Involved.provider_code == Region.provider_code),
                  isouter=True) \
            .join(District,
                  and_(Involved.home_district == District.id,
                       Involved.accident_year == District.year,
                       Involved.provider_code == District.provider_code),
                  isouter=True) \
            .join(NaturalArea,
                  and_(Involved.home_natural_area == NaturalArea.id,
                       Involved.accident_year == NaturalArea.year,
                       Involved.provider_code == NaturalArea.provider_code),
                  isouter=True) \
            .join(MunicipalStatus,
                  and_(Involved.home_municipal_status == MunicipalStatus.id,
                       Involved.accident_year == MunicipalStatus.year,
                       Involved.provider_code == MunicipalStatus.provider_code),
                  isouter=True) \
            .join(YishuvShape,
                  and_(Involved.home_yishuv_shape == YishuvShape.id,
                       Involved.accident_year == YishuvShape.year,
                       Involved.provider_code == YishuvShape.provider_code),
                  isouter=True) \
            .join(HospitalTime,
                  and_(Involved.hospital_time == HospitalTime.id,
                       Involved.accident_year == HospitalTime.year,
                       Involved.provider_code == HospitalTime.provider_code),
                  isouter=True) \
            .join(MedicalType,
                  and_(Involved.medical_type == MedicalType.id,
                       Involved.accident_year == MedicalType.year,
                       Involved.provider_code == MedicalType.provider_code),
                  isouter=True) \
            .join(ReleaseDest,
                  and_(Involved.release_dest == ReleaseDest.id,
                       Involved.accident_year == ReleaseDest.year,
                       Involved.provider_code == ReleaseDest.provider_code),
                  isouter=True) \
            .join(SafetyMeasuresUse,
                  and_(Involved.safety_measures_use == SafetyMeasuresUse.id,
                       Involved.accident_year == SafetyMeasuresUse.year,
                       Involved.provider_code == SafetyMeasuresUse.provider_code),
                  isouter=True) \
            .join(LateDeceased,
                  and_(Involved.late_deceased == LateDeceased.id,
                       Involved.accident_year == LateDeceased.year,
                       Involved.provider_code == LateDeceased.provider_code),
                  isouter=True)
        return select(selected_columns) \
            .select_from(from_clause)

    def __init__(self):
        self.MARKERS_HEBREW_VIEW = """SELECT markers.id,
                                        markers.provider_and_id,
                                        markers.provider_code,
                                        provider_code.provider_code_hebrew,
                                        markers.file_type_police,
                                        markers.accident_type,
                                        accident_type.accident_type_hebrew,
                                        markers.accident_severity,
                                        accident_severity.accident_severity_hebrew,
                                        markers.created as accident_timestamp,
                                        markers.location_accuracy,
                                        location_accuracy.location_accuracy_hebrew,
                                        markers.road_type,
                                        road_type.road_type_hebrew,
                                        markers.road_shape,
                                        road_shape.road_shape_hebrew,
                                        markers.day_type,
                                        day_type.day_type_hebrew,
                                        markers.police_unit,
                                        police_unit.police_unit_hebrew,
                                        markers.one_lane,
                                        one_lane.one_lane_hebrew,
                                        markers.multi_lane,
                                        multi_lane.multi_lane_hebrew,
                                        markers.speed_limit,
                                        speed_limit.speed_limit_hebrew,
                                        markers.road_intactness,
                                        road_intactness.road_intactness_hebrew,
                                        markers.road_width,
                                        road_width.road_width_hebrew,
                                        markers.road_sign,
                                        road_sign.road_sign_hebrew,
                                        markers.road_light,
                                        road_light.road_light_hebrew,
                                        markers.road_control,
                                        road_control.road_control_hebrew,
                                        markers.weather,
                                        weather.weather_hebrew,
                                        markers.road_surface,
                                        road_surface.road_surface_hebrew,
                                        markers.road_object,
                                        road_object.road_object_hebrew,
                                        markers.object_distance,
                                        object_distance.object_distance_hebrew,
                                        markers.didnt_cross,
                                        didnt_cross.didnt_cross_hebrew,
                                        markers.cross_mode,
                                        cross_mode.cross_mode_hebrew,
                                        markers.cross_location,
                                        cross_location.cross_location_hebrew,
                                        markers.cross_direction,
                                        cross_direction.cross_direction_hebrew,
                                        markers.road1,
                                        markers.road2,
                                        markers.km,
                                        markers.km_raw,
                                        markers.km_accurate,
                                        road_segments.segment_id as road_segment_id,
                                        road_segments.segment as road_segment_number,
                                        road_segments.from_name || ' - ' || road_segments.to_name as road_segment_name,
                                        road_segments.from_km as road_segment_from_km,
                                        road_segments.to_km as road_segment_to_km,
                                        road_segments.to_km - road_segments.from_km as road_segment_length_km,
                                        markers.yishuv_symbol,
                                        markers.yishuv_name,
                                        markers.geo_area,
                                        geo_area.geo_area_hebrew,
                                        markers.day_night,
                                        day_night.day_night_hebrew,
                                        markers.day_in_week,
                                        day_in_week.day_in_week_hebrew,
                                        markers.traffic_light,
                                        traffic_light.traffic_light_hebrew,
                                        markers.region,
                                        region.region_hebrew,
                                        markers.district,
                                        district.district_hebrew,
                                        markers.natural_area,
                                        natural_area.natural_area_hebrew,
                                        markers.municipal_status,
                                        municipal_status.municipal_status_hebrew,
                                        markers.yishuv_shape,
                                        yishuv_shape.yishuv_shape_hebrew,
                                        markers.street1,
                                        markers.street1_hebrew,
                                        markers.street2,
                                        markers.street2_hebrew,
                                        markers.house_number,
                                        markers.non_urban_intersection,
                                        markers.non_urban_intersection_hebrew,
                                        markers.non_urban_intersection_by_junction_number,
                                        markers.urban_intersection,
                                        markers.accident_year,
                                        markers.accident_month,
                                        markers.accident_day,
                                        markers.accident_hour_raw,
                                        accident_hour_raw.accident_hour_raw_hebrew,
                                        markers.accident_hour,
                                        markers.accident_minute,
                                        markers.geom,
                                        markers.longitude,
                                        markers.latitude,
                                        markers.x,
                                        markers.y
                                       FROM markers
                                         LEFT JOIN road_segments on (markers.road1 = road_segments.road) AND (road_segments.from_km <= markers.km / 10) AND (markers.km / 10 < road_segments.to_km)
                                         LEFT JOIN accident_type ON markers.accident_type = accident_type.id AND markers.accident_year = accident_type.year AND markers.provider_code = accident_type.provider_code
                                         LEFT JOIN accident_severity ON markers.accident_severity = accident_severity.id AND markers.accident_year = accident_severity.year AND markers.provider_code = accident_severity.provider_code
                                         LEFT JOIN location_accuracy ON markers.location_accuracy = location_accuracy.id AND markers.accident_year = location_accuracy.year AND markers.provider_code = location_accuracy.provider_code
                                         LEFT JOIN road_type ON markers.road_type = road_type.id AND markers.accident_year = road_type.year AND markers.provider_code = road_type.provider_code
                                         LEFT JOIN road_shape ON markers.road_shape = road_shape.id AND markers.accident_year = road_shape.year AND markers.provider_code = road_shape.provider_code
                                         LEFT JOIN day_type ON markers.day_type = day_type.id AND markers.accident_year = day_type.year AND markers.provider_code = day_type.provider_code
                                         LEFT JOIN police_unit ON markers.police_unit = police_unit.id AND markers.accident_year = police_unit.year AND markers.provider_code = police_unit.provider_code
                                         LEFT JOIN one_lane ON markers.one_lane = one_lane.id  AND markers.accident_year = one_lane.year AND markers.provider_code = one_lane.provider_code
                                         LEFT JOIN multi_lane ON markers.multi_lane = multi_lane.id AND markers.accident_year = multi_lane.year AND markers.provider_code = multi_lane.provider_code
                                         LEFT JOIN speed_limit ON markers.speed_limit = speed_limit.id AND markers.accident_year = speed_limit.year AND markers.provider_code = speed_limit.provider_code
                                         LEFT JOIN road_intactness ON markers.road_intactness = road_intactness.id AND markers.accident_year = road_intactness.year AND markers.provider_code = road_intactness.provider_code
                                         LEFT JOIN road_width ON markers.road_width = road_width.id AND markers.accident_year = road_width.year AND markers.provider_code = road_width.provider_code
                                         LEFT JOIN road_sign ON markers.road_sign = road_sign.id AND markers.accident_year = road_sign.year AND markers.provider_code = road_sign.provider_code
                                         LEFT JOIN road_light ON markers.road_light = road_light.id AND markers.accident_year = road_light.year AND markers.provider_code = road_light.provider_code
                                         LEFT JOIN road_control ON markers.road_control = road_control.id AND markers.accident_year = road_control.year AND markers.provider_code = road_control.provider_code
                                         LEFT JOIN weather ON markers.weather = weather.id AND markers.accident_year = weather.year AND markers.provider_code = weather.provider_code
                                         LEFT JOIN road_surface ON markers.road_surface = road_surface.id AND markers.accident_year = road_surface.year AND markers.provider_code = road_surface.provider_code
                                         LEFT JOIN road_object ON markers.road_object = road_object.id AND markers.accident_year = road_object.year AND markers.provider_code = road_object.provider_code
                                         LEFT JOIN object_distance ON markers.object_distance = object_distance.id AND markers.accident_year = object_distance.year AND markers.provider_code = object_distance.provider_code
                                         LEFT JOIN didnt_cross ON markers.didnt_cross = didnt_cross.id AND markers.accident_year = didnt_cross.year AND markers.provider_code = didnt_cross.provider_code
                                         LEFT JOIN cross_mode ON markers.cross_mode = cross_mode.id AND markers.accident_year = cross_mode.year AND markers.provider_code = cross_mode.provider_code
                                         LEFT JOIN cross_location ON markers.cross_location = cross_location.id AND markers.accident_year = cross_location.year AND markers.provider_code = cross_location.provider_code
                                         LEFT JOIN cross_direction ON markers.cross_direction = cross_direction.id AND markers.accident_year = cross_direction.year AND markers.provider_code = cross_direction.provider_code
                                         LEFT JOIN geo_area ON markers.geo_area = geo_area.id AND markers.accident_year = geo_area.year AND markers.provider_code = geo_area.provider_code
                                         LEFT JOIN day_night ON markers.day_night = day_night.id AND markers.accident_year = day_night.year AND markers.provider_code = day_night.provider_code
                                         LEFT JOIN day_in_week ON markers.day_in_week = day_in_week.id AND markers.accident_year = day_in_week.year AND markers.provider_code = day_in_week.provider_code
                                         LEFT JOIN traffic_light ON markers.traffic_light = traffic_light.id AND markers.accident_year = traffic_light.year AND markers.provider_code = traffic_light.provider_code
                                         LEFT JOIN region ON markers.region = region.id AND markers.accident_year = region.year AND markers.provider_code = region.provider_code
                                         LEFT JOIN district ON markers.district = district.id AND markers.accident_year = district.year AND markers.provider_code = district.provider_code
                                         LEFT JOIN natural_area ON markers.natural_area = natural_area.id AND markers.accident_year = natural_area.year AND markers.provider_code = natural_area.provider_code
                                         LEFT JOIN municipal_status ON markers.municipal_status = municipal_status.id AND markers.accident_year = municipal_status.year AND markers.provider_code = municipal_status.provider_code
                                         LEFT JOIN yishuv_shape ON markers.yishuv_shape = yishuv_shape.id AND markers.accident_year = yishuv_shape.year AND markers.provider_code = yishuv_shape.provider_code
                                         LEFT JOIN accident_hour_raw ON markers.accident_hour_raw = accident_hour_raw.id AND markers.accident_year = accident_hour_raw.year AND markers.provider_code = accident_hour_raw.provider_code
                                         LEFT JOIN provider_code ON markers.provider_code = provider_code.id;"""

        self.INVOLVED_HEBREW_VIEW = """SELECT
        involved.accident_id,
        involved.provider_and_id,
        involved.provider_code,
        involved.file_type_police,
        involved.involved_type,
        involved_type.involved_type_hebrew,
        involved.license_acquiring_date,
        involved.age_group,
        age_group.age_group_hebrew,
        involved.sex,
        sex.sex_hebrew,
        involved.vehicle_type,
        vehicle_type.vehicle_type_hebrew,
        involved.safety_measures,
        safety_measures.safety_measures_hebrew,
        involved.involve_yishuv_symbol,
        involved.involve_yishuv_name,
        involved.injury_severity,
        injury_severity.injury_severity_hebrew,
        involved.injured_type,
        injured_type.injured_type_hebrew,
        involved.injured_position,
        injured_position.injured_position_hebrew,
        involved.population_type,
        population_type.population_type_hebrew,
        involved.home_region,
        region.region_hebrew as home_region_hebrew,
        involved.home_district,
        district.district_hebrew AS home_district_hebrew,
        involved.home_natural_area,
        natural_area.natural_area_hebrew AS home_natural_area_hebrew,
        involved.home_municipal_status,
        municipal_status.municipal_status_hebrew as home_municipal_status_hebrew,
        involved.home_yishuv_shape,
        yishuv_shape.yishuv_shape_hebrew AS home_yishuv_shape_hebrew,
        involved.hospital_time,
        hospital_time.hospital_time_hebrew,
        involved.medical_type,
        medical_type.medical_type_hebrew,
        involved.release_dest,
        release_dest.release_dest_hebrew,
        involved.safety_measures_use,
        safety_measures_use.safety_measures_use_hebrew,
        involved.late_deceased,
        late_deceased.late_deceased_hebrew,
        involved.car_id,
        involved.involve_id,
        involved.accident_year,
        involved.accident_month
       FROM involved
         LEFT JOIN involved_type ON involved.involved_type = involved_type.id AND involved.accident_year = involved_type.year AND involved.provider_code = involved_type.provider_code
         LEFT JOIN age_group ON involved.age_group = age_group.id  AND involved.accident_year = age_group.year AND involved.provider_code = age_group.provider_code
         LEFT JOIN sex ON involved.sex = sex.id AND involved.accident_year = sex.year AND involved.provider_code = sex.provider_code
         LEFT JOIN vehicle_type ON involved.vehicle_type = vehicle_type.id AND involved.accident_year = vehicle_type.year AND involved.provider_code = vehicle_type.provider_code
         LEFT JOIN safety_measures ON involved.safety_measures = safety_measures.id AND involved.accident_year = safety_measures.year AND involved.provider_code = safety_measures.provider_code
         LEFT JOIN injury_severity ON involved.injury_severity = injury_severity.id AND involved.accident_year = injury_severity.year AND involved.provider_code = injury_severity.provider_code
         LEFT JOIN injured_type ON involved.injured_type = injured_type.id AND involved.accident_year = injured_type.year AND involved.provider_code = injured_type.provider_code
         LEFT JOIN injured_position ON involved.injured_position = injured_position.id AND involved.accident_year = injured_position.year AND involved.provider_code = injured_position.provider_code
         LEFT JOIN population_type ON involved.population_type = population_type.id AND involved.accident_year = population_type.year AND involved.provider_code = population_type.provider_code
         LEFT JOIN region ON involved.home_region = region.id AND involved.accident_year = region.year AND involved.provider_code = region.provider_code
         LEFT JOIN district ON involved.home_district = district.id AND involved.accident_year = district.year AND involved.provider_code = district.provider_code
         LEFT JOIN natural_area ON involved.home_natural_area = natural_area.id AND involved.accident_year = natural_area.year AND involved.provider_code = natural_area.provider_code
         LEFT JOIN municipal_status ON involved.home_municipal_status = municipal_status.id AND involved.accident_year = municipal_status.year AND involved.provider_code = municipal_status.provider_code
         LEFT JOIN yishuv_shape ON involved.home_yishuv_shape = yishuv_shape.id AND involved.accident_year = yishuv_shape.year AND involved.provider_code = yishuv_shape.provider_code
         LEFT JOIN hospital_time ON involved.hospital_time = hospital_time.id AND involved.accident_year = hospital_time.year AND involved.provider_code = hospital_time.provider_code
         LEFT JOIN medical_type ON involved.medical_type = medical_type.id AND involved.accident_year = medical_type.year AND involved.provider_code = medical_type.provider_code
         LEFT JOIN release_dest ON involved.release_dest = release_dest.id AND involved.accident_year = release_dest.year AND involved.provider_code = release_dest.provider_code
         LEFT JOIN safety_measures_use ON involved.safety_measures_use = safety_measures_use.id AND involved.accident_year = safety_measures_use.year AND involved.provider_code = safety_measures_use.provider_code
         LEFT JOIN late_deceased ON involved.late_deceased = late_deceased.id AND involved.accident_year = late_deceased.year AND involved.provider_code = late_deceased.provider_code;"""

        self.VEHICLES_HEBREW_VIEW = """ SELECT
        vehicles.id,
        vehicles.accident_id,
        vehicles.provider_and_id,
        vehicles.provider_code,
        vehicles.file_type_police,
        vehicles.car_id,
        vehicles.engine_volume,
        engine_volume.engine_volume_hebrew,
        vehicles.manufacturing_year,
        vehicles.driving_directions,
        driving_directions.driving_directions_hebrew,
        vehicles.vehicle_status,
        vehicle_status.vehicle_status_hebrew,
        vehicles.vehicle_attribution,
        vehicle_attribution.vehicle_attribution_hebrew,
        vehicles.seats,
        vehicles.total_weight,
        total_weight.total_weight_hebrew,
        vehicles.vehicle_type,
        vehicle_type.vehicle_type_hebrew,
        vehicles.vehicle_damage,
        vehicle_damage.vehicle_damage_hebrew,
        vehicles.accident_year,
        vehicles.accident_month
       FROM vehicles
         LEFT JOIN engine_volume ON vehicles.engine_volume = engine_volume.id AND vehicles.accident_year = engine_volume.year AND vehicles.provider_code = engine_volume.provider_code
         LEFT JOIN driving_directions ON vehicles.driving_directions = driving_directions.id AND vehicles.accident_year = driving_directions.year AND vehicles.provider_code = driving_directions.provider_code
         LEFT JOIN vehicle_status ON vehicles.vehicle_status = vehicle_status.id AND vehicles.accident_year = vehicle_status.year AND vehicles.provider_code = vehicle_status.provider_code
         LEFT JOIN vehicle_attribution ON vehicles.vehicle_attribution = vehicle_attribution.id AND vehicles.accident_year = vehicle_attribution.year AND vehicles.provider_code = vehicle_attribution.provider_code
         LEFT JOIN total_weight ON vehicles.total_weight = total_weight.id AND vehicles.accident_year = total_weight.year AND vehicles.provider_code = total_weight.provider_code
         LEFT JOIN vehicle_type ON vehicles.vehicle_type = vehicle_type.id AND vehicles.accident_year = vehicle_type.year AND vehicles.provider_code = vehicle_type.provider_code
         LEFT JOIN vehicle_damage ON vehicles.vehicle_damage = vehicle_damage.id AND vehicles.accident_year = vehicle_damage.year AND vehicles.provider_code = vehicle_damage.provider_code;"""

        self.INVOLVED_HEBREW_MARKERS_HEBREW_VIEW = """SELECT
        involved_hebrew.accident_id,
        involved_hebrew.provider_and_id,
        involved_hebrew.provider_code,
        involved_hebrew.file_type_police,
        involved_hebrew.involved_type,
        involved_hebrew.involved_type_hebrew,
        involved_hebrew.license_acquiring_date,
        involved_hebrew.age_group,
        involved_hebrew.age_group_hebrew,
        involved_hebrew.sex,
        involved_hebrew.sex_hebrew,
        involved_hebrew.vehicle_type as involve_vehicle_type,
        involved_hebrew.vehicle_type_hebrew as involve_vehicle_type_hebrew,
        involved_hebrew.safety_measures,
        involved_hebrew.safety_measures_hebrew,
        involved_hebrew.involve_yishuv_symbol,
        involved_hebrew.involve_yishuv_name,
        involved_hebrew.injury_severity,
        involved_hebrew.injury_severity_hebrew,
        involved_hebrew.injured_type,
        involved_hebrew.injured_type_hebrew,
        involved_hebrew.injured_position,
        involved_hebrew.injured_position_hebrew,
        involved_hebrew.population_type,
        involved_hebrew.population_type_hebrew,
        involved_hebrew.home_region as involve_home_region,
        involved_hebrew.home_region_hebrew as involve_home_region_hebrew,
        involved_hebrew.home_district as involve_home_district,
        involved_hebrew.home_district_hebrew as involve_home_district_hebrew,
        involved_hebrew.home_natural_area as involve_home_natural_area,
        involved_hebrew.home_natural_area_hebrew as involve_home_natural_area_hebrew,
        involved_hebrew.home_municipal_status as involve_home_municipal_status,
        involved_hebrew.home_municipal_status_hebrew as involve_home_municipal_status_hebrew,
        involved_hebrew.home_yishuv_shape as involve_home_yishuv_shape,
        involved_hebrew.home_yishuv_shape_hebrew as involve_home_yishuv_shape_hebrew,
        involved_hebrew.hospital_time,
        involved_hebrew.hospital_time_hebrew,
        involved_hebrew.medical_type,
        involved_hebrew.medical_type_hebrew,
        involved_hebrew.release_dest,
        involved_hebrew.release_dest_hebrew,
        involved_hebrew.safety_measures_use,
        involved_hebrew.safety_measures_use_hebrew,
        involved_hebrew.late_deceased,
        involved_hebrew.late_deceased_hebrew,
        involved_hebrew.car_id,
        involved_hebrew.involve_id,
        involved_hebrew.accident_year,
        involved_hebrew.accident_month,
        markers_hebrew.provider_code_hebrew,
        markers_hebrew.accident_timestamp,
        markers_hebrew.accident_type,
        markers_hebrew.accident_type_hebrew,
        markers_hebrew.accident_severity,
        markers_hebrew.accident_severity_hebrew,
        markers_hebrew.location_accuracy,
        markers_hebrew.location_accuracy_hebrew,
        markers_hebrew.road_type,
        markers_hebrew.road_type_hebrew,
        markers_hebrew.road_shape,
        markers_hebrew.road_shape_hebrew,
        markers_hebrew.day_type,
        markers_hebrew.day_type_hebrew,
        markers_hebrew.police_unit,
        markers_hebrew.police_unit_hebrew,
        markers_hebrew.one_lane,
        markers_hebrew.one_lane_hebrew,
        markers_hebrew.multi_lane,
        markers_hebrew.multi_lane_hebrew,
        markers_hebrew.speed_limit,
        markers_hebrew.speed_limit_hebrew,
        markers_hebrew.road_intactness,
        markers_hebrew.road_intactness_hebrew,
        markers_hebrew.road_width,
        markers_hebrew.road_width_hebrew,
        markers_hebrew.road_sign,
        markers_hebrew.road_sign_hebrew,
        markers_hebrew.road_light,
        markers_hebrew.road_light_hebrew,
        markers_hebrew.road_control,
        markers_hebrew.road_control_hebrew,
        markers_hebrew.weather,
        markers_hebrew.weather_hebrew,
        markers_hebrew.road_surface,
        markers_hebrew.road_surface_hebrew,
        markers_hebrew.road_object,
        markers_hebrew.road_object_hebrew,
        markers_hebrew.object_distance,
        markers_hebrew.object_distance_hebrew,
        markers_hebrew.didnt_cross,
        markers_hebrew.didnt_cross_hebrew,
        markers_hebrew.cross_mode,
        markers_hebrew.cross_mode_hebrew,
        markers_hebrew.cross_location,
        markers_hebrew.cross_location_hebrew,
        markers_hebrew.cross_direction,
        markers_hebrew.cross_direction_hebrew,
        markers_hebrew.road1,
        markers_hebrew.road2,
        markers_hebrew.km,
        markers_hebrew.km_raw,
        markers_hebrew.km_accurate,
        markers_hebrew.road_segment_id,
        markers_hebrew.road_segment_number,
        markers_hebrew.road_segment_name,
        markers_hebrew.road_segment_from_km,
        markers_hebrew.road_segment_to_km,
        markers_hebrew.road_segment_length_km,
        markers_hebrew.yishuv_symbol as accident_yishuv_symbol,
        markers_hebrew.yishuv_name as accident_yishuv_name,
        markers_hebrew.geo_area,
        markers_hebrew.geo_area_hebrew,
        markers_hebrew.day_night,
        markers_hebrew.day_night_hebrew,
        markers_hebrew.day_in_week,
        markers_hebrew.day_in_week_hebrew,
        markers_hebrew.traffic_light,
        markers_hebrew.traffic_light_hebrew,
        markers_hebrew.region as accident_region,
        markers_hebrew.region_hebrew as accident_region_hebrew,
        markers_hebrew.district as accident_district,
        markers_hebrew.district_hebrew as accident_district_hebrew,
        markers_hebrew.natural_area as accident_natural_area,
        markers_hebrew.natural_area_hebrew as accident_natural_area_hebrew,
        markers_hebrew.municipal_status as accident_municipal_status,
        markers_hebrew.municipal_status_hebrew as accident_municipal_status_hebrew,
        markers_hebrew.yishuv_shape as accident_yishuv_shape,
        markers_hebrew.yishuv_shape_hebrew as accident_yishuv_shape_hebrew,
        markers_hebrew.street1,
        markers_hebrew.street1_hebrew,
        markers_hebrew.street2,
        markers_hebrew.street2_hebrew,
        markers_hebrew.non_urban_intersection,
        markers_hebrew.non_urban_intersection_hebrew,
        markers_hebrew.non_urban_intersection_by_junction_number,
        markers_hebrew.accident_day,
        markers_hebrew.accident_hour_raw,
        markers_hebrew.accident_hour_raw_hebrew,
        markers_hebrew.accident_hour,
        markers_hebrew.accident_minute,
        markers_hebrew.geom,
        markers_hebrew.longitude,
        markers_hebrew.latitude,
        markers_hebrew.x,
        markers_hebrew.y,
        vehicles_hebrew.engine_volume,
        vehicles_hebrew.engine_volume_hebrew,
        vehicles_hebrew.manufacturing_year,
        vehicles_hebrew.driving_directions,
        vehicles_hebrew.driving_directions_hebrew,
        vehicles_hebrew.vehicle_status,
        vehicles_hebrew.vehicle_status_hebrew,
        vehicles_hebrew.vehicle_attribution,
        vehicles_hebrew.vehicle_attribution_hebrew,
        vehicles_hebrew.seats,
        vehicles_hebrew.total_weight,
        vehicles_hebrew.total_weight_hebrew,
        vehicles_hebrew.vehicle_type as vehicle_vehicle_type,
        vehicles_hebrew.vehicle_type_hebrew as vehicle_vehicle_type_hebrew,
        vehicles_hebrew.vehicle_damage,
        vehicles_hebrew.vehicle_damage_hebrew
         FROM involved_hebrew
         LEFT JOIN markers_hebrew ON involved_hebrew.provider_code = markers_hebrew.provider_code
                                  AND involved_hebrew.accident_id = markers_hebrew.id
                                  AND involved_hebrew.accident_year = markers_hebrew.accident_year
         LEFT JOIN vehicles_hebrew ON involved_hebrew.provider_code = vehicles_hebrew.provider_code
                                  AND involved_hebrew.accident_id = vehicles_hebrew.accident_id
                                  AND involved_hebrew.accident_year = vehicles_hebrew.accident_year
                                  AND involved_hebrew.car_id = vehicles_hebrew.car_id ;"""

        self.VEHICLES_MARKERS_HEBREW_VIEW = """ SELECT
        markers_hebrew.accident_timestamp,
        markers_hebrew.accident_type,
        markers_hebrew.accident_type_hebrew,
        markers_hebrew.accident_severity,
        markers_hebrew.accident_severity_hebrew,
        markers_hebrew.location_accuracy,
        markers_hebrew.location_accuracy_hebrew,
        markers_hebrew.road_type,
        markers_hebrew.road_type_hebrew,
        markers_hebrew.road_shape,
        markers_hebrew.road_shape_hebrew,
        markers_hebrew.day_type,
        markers_hebrew.day_type_hebrew,
        markers_hebrew.police_unit,
        markers_hebrew.police_unit_hebrew,
        markers_hebrew.one_lane,
        markers_hebrew.one_lane_hebrew,
        markers_hebrew.multi_lane,
        markers_hebrew.multi_lane_hebrew,
        markers_hebrew.speed_limit,
        markers_hebrew.speed_limit_hebrew,
        markers_hebrew.road_intactness,
        markers_hebrew.road_intactness_hebrew,
        markers_hebrew.road_width,
        markers_hebrew.road_width_hebrew,
        markers_hebrew.road_sign,
        markers_hebrew.road_sign_hebrew,
        markers_hebrew.road_light,
        markers_hebrew.road_light_hebrew,
        markers_hebrew.road_control,
        markers_hebrew.road_control_hebrew,
        markers_hebrew.weather,
        markers_hebrew.weather_hebrew,
        markers_hebrew.road_surface,
        markers_hebrew.road_surface_hebrew,
        markers_hebrew.road_object,
        markers_hebrew.road_object_hebrew,
        markers_hebrew.object_distance,
        markers_hebrew.object_distance_hebrew,
        markers_hebrew.didnt_cross,
        markers_hebrew.didnt_cross_hebrew,
        markers_hebrew.cross_mode,
        markers_hebrew.cross_mode_hebrew,
        markers_hebrew.cross_location,
        markers_hebrew.cross_location_hebrew,
        markers_hebrew.cross_direction,
        markers_hebrew.cross_direction_hebrew,
        markers_hebrew.road1,
        markers_hebrew.road2,
        markers_hebrew.km,
        markers_hebrew.km_raw,
        markers_hebrew.km_accurate,
        markers_hebrew.road_segment_id,
        markers_hebrew.road_segment_number,
        markers_hebrew.road_segment_name,
        markers_hebrew.road_segment_from_km,
        markers_hebrew.road_segment_to_km,
        markers_hebrew.road_segment_length_km,
        markers_hebrew.yishuv_symbol as accident_yishuv_symbol,
        markers_hebrew.yishuv_name as accident_yishuv_name,
        markers_hebrew.geo_area,
        markers_hebrew.geo_area_hebrew,
        markers_hebrew.day_night,
        markers_hebrew.day_night_hebrew,
        markers_hebrew.day_in_week,
        markers_hebrew.day_in_week_hebrew,
        markers_hebrew.traffic_light,
        markers_hebrew.traffic_light_hebrew,
        markers_hebrew.region as accident_region,
        markers_hebrew.region_hebrew as accident_region_hebrew,
        markers_hebrew.district as accident_district,
        markers_hebrew.district_hebrew as accident_district_hebrew,
        markers_hebrew.natural_area as accident_natural_area,
        markers_hebrew.natural_area_hebrew as accident_natural_area_hebrew,
        markers_hebrew.municipal_status as accident_municipal_status,
        markers_hebrew.municipal_status_hebrew as accident_municipal_status_hebrew,
        markers_hebrew.yishuv_shape as accident_yishuv_shape,
        markers_hebrew.yishuv_shape_hebrew as accident_yishuv_shape_hebrew,
        markers_hebrew.street1,
        markers_hebrew.street1_hebrew,
        markers_hebrew.street2,
        markers_hebrew.street2_hebrew,
        markers_hebrew.non_urban_intersection,
        markers_hebrew.non_urban_intersection_hebrew,
        markers_hebrew.non_urban_intersection_by_junction_number,
        markers_hebrew.accident_day,
        markers_hebrew.accident_hour_raw,
        markers_hebrew.accident_hour_raw_hebrew,
        markers_hebrew.accident_hour,
        markers_hebrew.accident_minute,
        markers_hebrew.accident_year,
        markers_hebrew.accident_month,
        markers_hebrew.geom,
        markers_hebrew.longitude,
        markers_hebrew.latitude,
        markers_hebrew.x,
        markers_hebrew.y,
        vehicles_hebrew.id,
        vehicles_hebrew.accident_id,
        vehicles_hebrew.provider_and_id,
        vehicles_hebrew.provider_code,
        vehicles_hebrew.file_type_police,
        vehicles_hebrew.engine_volume,
        vehicles_hebrew.engine_volume_hebrew,
        vehicles_hebrew.manufacturing_year,
        vehicles_hebrew.driving_directions,
        vehicles_hebrew.driving_directions_hebrew,
        vehicles_hebrew.vehicle_status,
        vehicles_hebrew.vehicle_status_hebrew,
        vehicles_hebrew.vehicle_attribution,
        vehicles_hebrew.vehicle_attribution_hebrew,
        vehicles_hebrew.seats,
        vehicles_hebrew.total_weight,
        vehicles_hebrew.total_weight_hebrew,
        vehicles_hebrew.vehicle_type,
        vehicles_hebrew.vehicle_type_hebrew,
        vehicles_hebrew.vehicle_damage,
        vehicles_hebrew.vehicle_damage_hebrew,
        vehicles_hebrew.car_id
       FROM vehicles_hebrew
        INNER JOIN markers_hebrew ON vehicles_hebrew.provider_code = markers_hebrew.provider_code
                                 AND vehicles_hebrew.accident_id = markers_hebrew.id
                                 AND vehicles_hebrew.accident_year = markers_hebrew.accident_year ;"""


    def create_involved_hebrew_markers_hebrew_view(self):
        selected_columns = [
            InvolvedView.accident_id,
            InvolvedView.provider_and_id,
            InvolvedView.provider_code,
            InvolvedView.file_type_police,
            InvolvedView.involved_type,
            InvolvedView.involved_type_hebrew,
            InvolvedView.license_acquiring_date,
            InvolvedView.age_group,
            InvolvedView.age_group_hebrew,
            InvolvedView.sex,
            InvolvedView.sex_hebrew,
            InvolvedView.vehicle_type.label("involve_vehicle_type"),
            InvolvedView.vehicle_type_hebrew.label("involve_vehicle_type_hebrew"),
            InvolvedView.safety_measures,
            InvolvedView.safety_measures_hebrew,
            InvolvedView.involve_yishuv_symbol,
            InvolvedView.involve_yishuv_name,
            InvolvedView.injury_severity,
            InvolvedView.injury_severity_hebrew,
            InvolvedView.injured_type,
            InvolvedView.injured_type_hebrew,
            InvolvedView.injured_position,
            InvolvedView.injured_position_hebrew,
            InvolvedView.population_type,
            InvolvedView.population_type_hebrew,
            InvolvedView.home_region.label("involve_home_region"),
            InvolvedView.home_region_hebrew.label("involve_home_region_hebrew"),
            InvolvedView.home_district.label("involve_home_district"),
            InvolvedView.home_district_hebrew.label("involve_home_district_hebrew"),
            InvolvedView.home_natural_area.label("involve_home_natural_area"),
            InvolvedView.home_natural_area_hebrew.label("involve_home_natural_area_hebrew"),
            InvolvedView.home_municipal_status.label("involve_home_municipal_status"),
            InvolvedView.home_municipal_status_hebrew.label("involve_home_municipal_status_hebrew"),
            InvolvedView.home_yishuv_shape.label("involve_home_yishuv_shape"),
            InvolvedView.home_yishuv_shape_hebrew.label("involve_home_yishuv_shape_hebrew"),
            InvolvedView.hospital_time,
            InvolvedView.hospital_time_hebrew,
            InvolvedView.medical_type,
            InvolvedView.medical_type_hebrew,
            InvolvedView.release_dest,
            InvolvedView.release_dest_hebrew,
            InvolvedView.safety_measures_use,
            InvolvedView.safety_measures_use_hebrew,
            InvolvedView.late_deceased,
            InvolvedView.late_deceased_hebrew,
            InvolvedView.car_id,
            InvolvedView.involve_id,
            InvolvedView.accident_year,
            InvolvedView.accident_month,
            AccidentMarkerView.provider_code_hebrew,
            AccidentMarkerView.accident_timestamp,
            AccidentMarkerView.accident_type,
            AccidentMarkerView.accident_type_hebrew,
            AccidentMarkerView.accident_severity,
            AccidentMarkerView.accident_severity_hebrew,
            AccidentMarkerView.location_accuracy,
            AccidentMarkerView.location_accuracy_hebrew,
            AccidentMarkerView.road_type,
            AccidentMarkerView.road_type_hebrew,
            AccidentMarkerView.road_shape,
            AccidentMarkerView.road_shape_hebrew,
            AccidentMarkerView.day_type,
            AccidentMarkerView.day_type_hebrew,
            AccidentMarkerView.police_unit,
            AccidentMarkerView.police_unit_hebrew,
            AccidentMarkerView.one_lane,
            AccidentMarkerView.one_lane_hebrew,
            AccidentMarkerView.multi_lane,
            AccidentMarkerView.multi_lane_hebrew,
            AccidentMarkerView.speed_limit,
            AccidentMarkerView.speed_limit_hebrew,
            AccidentMarkerView.road_intactness,
            AccidentMarkerView.road_intactness_hebrew,
            AccidentMarkerView.road_width,
            AccidentMarkerView.road_width_hebrew,
            AccidentMarkerView.road_sign,
            AccidentMarkerView.road_sign_hebrew,
            AccidentMarkerView.road_light,
            AccidentMarkerView.road_light_hebrew,
            AccidentMarkerView.road_control,
            AccidentMarkerView.road_control_hebrew,
            AccidentMarkerView.weather,
            AccidentMarkerView.weather_hebrew,
            AccidentMarkerView.road_surface,
            AccidentMarkerView.road_surface_hebrew,
            AccidentMarkerView.road_object,
            AccidentMarkerView.road_object_hebrew,
            AccidentMarkerView.object_distance,
            AccidentMarkerView.object_distance_hebrew,
            AccidentMarkerView.didnt_cross,
            AccidentMarkerView.didnt_cross_hebrew,
            AccidentMarkerView.cross_mode,
            AccidentMarkerView.cross_mode_hebrew,
            AccidentMarkerView.cross_location,
            AccidentMarkerView.cross_location_hebrew,
            AccidentMarkerView.cross_direction,
            AccidentMarkerView.cross_direction_hebrew,
            AccidentMarkerView.road1,
            AccidentMarkerView.road2,
            AccidentMarkerView.km,
            AccidentMarkerView.km_raw,
            AccidentMarkerView.km_accurate,
            AccidentMarkerView.road_segment_id,
            AccidentMarkerView.road_segment_number,
            AccidentMarkerView.road_segment_name,
            AccidentMarkerView.road_segment_from_km,
            AccidentMarkerView.road_segment_to_km,
            AccidentMarkerView.road_segment_length_km,
            AccidentMarkerView.yishuv_symbol.label("accident_yishuv_symbol"),
            AccidentMarkerView.yishuv_name.label("ccident_yishuv_name"),
            AccidentMarkerView.geo_area,
            AccidentMarkerView.geo_area_hebrew,
            AccidentMarkerView.day_night,
            AccidentMarkerView.day_night_hebrew,
            AccidentMarkerView.day_in_week,
            AccidentMarkerView.day_in_week_hebrew,
            AccidentMarkerView.traffic_light,
            AccidentMarkerView.traffic_light_hebrew,
            AccidentMarkerView.region.label("accident_region"),
            AccidentMarkerView.region_hebrew.label("accident_region_hebrew"),
            AccidentMarkerView.district.label("accident_district"),
            AccidentMarkerView.district_hebrew.label("accident_district_hebrew"),
            AccidentMarkerView.natural_area.label("accident_natural_area"),
            AccidentMarkerView.natural_area_hebrew.label("accident_natural_area_hebrew"),
            AccidentMarkerView.municipal_status.label("accident_municipal_status"),
            AccidentMarkerView.municipal_status_hebrew.label("accident_municipal_status_hebrew"),
            AccidentMarkerView.yishuv_shape.label("accident_yishuv_shape"),
            AccidentMarkerView.yishuv_shape_hebrew.label("accident_yishuv_shape_hebrew"),
            AccidentMarkerView.street1,
            AccidentMarkerView.street1_hebrew,
            AccidentMarkerView.street2,
            AccidentMarkerView.street2_hebrew,
            AccidentMarkerView.non_urban_intersection,
            AccidentMarkerView.non_urban_intersection_hebrew,
            AccidentMarkerView.non_urban_intersection_by_junction_number,
            AccidentMarkerView.accident_day,
            AccidentMarkerView.accident_hour_raw,
            AccidentMarkerView.accident_hour_raw_hebrew,
            AccidentMarkerView.accident_hour,
            AccidentMarkerView.accident_minute,
            AccidentMarkerView.geom,
            AccidentMarkerView.longitude,
            AccidentMarkerView.latitude,
            AccidentMarkerView.x,
            AccidentMarkerView.y,
            VehiclesView.engine_volume,
            VehiclesView.engine_volume_hebrew,
            VehiclesView.manufacturing_year,
            VehiclesView.driving_directions,
            VehiclesView.driving_directions_hebrew,
            VehiclesView.vehicle_status,
            VehiclesView.vehicle_status_hebrew,
            VehiclesView.vehicle_attribution,
            VehiclesView.vehicle_attribution_hebrew,
            VehiclesView.seats,
            VehiclesView.total_weight,
            VehiclesView.total_weight_hebrew,
            VehiclesView.vehicle_type.label("vehicle_vehicle_type"),
            VehiclesView.vehicle_type_hebrew.label("vehicle_vehicle_type_hebrew"),
            VehiclesView.vehicle_damage,
            VehiclesView.vehicle_damage_hebrew
        ]
        table = InvolvedView.__table__
        from_clause = table \
            .join(AccidentMarkerView,
                  and_(InvolvedView.provider_code == AccidentMarkerView.provider_code,
                       InvolvedView.accident_id == AccidentMarkerView.id,
                       InvolvedView.accident_year == AccidentMarkerView.accident_year),
                  isouter=True) \
            .join(VehiclesView,
                  and_(InvolvedView.provider_code == VehiclesView.provider_code,
                       InvolvedView.accident_id == VehiclesView.accident_id,
                       InvolvedView.accident_year == VehiclesView.accident_year,
                       InvolvedView.car_id == VehiclesView.car_id),
                  isouter=True)
        return select(selected_columns) \
            .select_from(from_clause)

    def create_vehicles_hebrew_view(self):
        selected_columns = [
            Vehicle.id,
            Vehicle.accident_id,
            Vehicle.provider_and_id,
            Vehicle.provider_code,
            Vehicle.file_type_police,
            Vehicle.car_id,
            Vehicle.engine_volume,
            EngineVolume.engine_volume_hebrew,
            Vehicle.manufacturing_year,
            Vehicle.driving_directions,
            DrivingDirections.driving_directions_hebrew,
            Vehicle.vehicle_status,
            VehicleStatus.vehicle_status_hebrew,
            Vehicle.vehicle_attribution,
            VehicleAttribution.vehicle_attribution_hebrew,
            Vehicle.seats,
            Vehicle.total_weight,
            TotalWeight.total_weight_hebrew,
            Vehicle.vehicle_type,
            VehicleType.vehicle_type_hebrew,
            Vehicle.vehicle_damage,
            VehicleDamage.vehicle_damage_hebrew,
            Vehicle.accident_year,
            Vehicle.accident_month
        ]
        table = Vehicle.__table__
        from_clause = table \
            .join(EngineVolume,
                  and_(Vehicle.engine_volume == EngineVolume.id,
                       Vehicle.accident_year == EngineVolume.year,
                       Vehicle.provider_code == EngineVolume.provider_code),
                  isouter=True) \
            .join(DrivingDirections,
                  and_(Vehicle.driving_directions == DrivingDirections.id,
                       Vehicle.accident_year == DrivingDirections.year,
                       Vehicle.provider_code == DrivingDirections.provider_code),
                  isouter=True) \
            .join(VehicleStatus,
                  and_(Vehicle.vehicle_status == VehicleStatus.id,
                       Vehicle.accident_year == VehicleStatus.year,
                       Vehicle.provider_code == VehicleStatus.provider_code),
                  isouter=True) \
            .join(VehicleAttribution,
                  and_(Vehicle.vehicle_attribution == VehicleAttribution.id,
                       Vehicle.accident_year == VehicleAttribution.year,
                       Vehicle.provider_code == VehicleAttribution.provider_code),
                  isouter=True) \
            .join(TotalWeight,
                  and_(Vehicle.total_weight == TotalWeight.id,
                       Vehicle.accident_year == TotalWeight.year,
                       Vehicle.provider_code == TotalWeight.provider_code),
                  isouter=True) \
            .join(VehicleType,
                  and_(Vehicle.vehicle_type == VehicleType.id,
                       Vehicle.accident_year == VehicleType.year,
                       Vehicle.provider_code == VehicleType.provider_code),
                  isouter=True) \
            .join(VehicleDamage,
                  and_(Vehicle.vehicle_damage == VehicleDamage.id,
                       Vehicle.accident_year == VehicleDamage.year,
                       Vehicle.provider_code == VehicleDamage.provider_code),
                  isouter=True)
        return select(selected_columns) \
            .select_from(from_clause)

    def create_vehicles_markers_hebrew_view(self):
        selected_columns = [
            AccidentMarkerView.accident_timestamp,
            AccidentMarkerView.accident_type,
            AccidentMarkerView.accident_type_hebrew,
            AccidentMarkerView.accident_severity,
            AccidentMarkerView.accident_severity_hebrew,
            AccidentMarkerView.location_accuracy,
            AccidentMarkerView.location_accuracy_hebrew,
            AccidentMarkerView.road_type,
            AccidentMarkerView.road_type_hebrew,
            AccidentMarkerView.road_shape,
            AccidentMarkerView.road_shape_hebrew,
            AccidentMarkerView.day_type,
            AccidentMarkerView.day_type_hebrew,
            AccidentMarkerView.police_unit,
            AccidentMarkerView.police_unit_hebrew,
            AccidentMarkerView.one_lane,
            AccidentMarkerView.one_lane_hebrew,
            AccidentMarkerView.multi_lane,
            AccidentMarkerView.multi_lane_hebrew,
            AccidentMarkerView.speed_limit,
            AccidentMarkerView.speed_limit_hebrew,
            AccidentMarkerView.road_intactness,
            AccidentMarkerView.road_intactness_hebrew,
            AccidentMarkerView.road_width,
            AccidentMarkerView.road_width_hebrew,
            AccidentMarkerView.road_sign,
            AccidentMarkerView.road_sign_hebrew,
            AccidentMarkerView.road_light,
            AccidentMarkerView.road_light_hebrew,
            AccidentMarkerView.road_control,
            AccidentMarkerView.road_control_hebrew,
            AccidentMarkerView.weather,
            AccidentMarkerView.weather_hebrew,
            AccidentMarkerView.road_surface,
            AccidentMarkerView.road_surface_hebrew,
            AccidentMarkerView.road_object,
            AccidentMarkerView.road_object_hebrew,
            AccidentMarkerView.object_distance,
            AccidentMarkerView.object_distance_hebrew,
            AccidentMarkerView.didnt_cross,
            AccidentMarkerView.didnt_cross_hebrew,
            AccidentMarkerView.cross_mode,
            AccidentMarkerView.cross_mode_hebrew,
            AccidentMarkerView.cross_location,
            AccidentMarkerView.cross_location_hebrew,
            AccidentMarkerView.cross_direction,
            AccidentMarkerView.cross_direction_hebrew,
            AccidentMarkerView.road1,
            AccidentMarkerView.road2,
            AccidentMarkerView.km,
            AccidentMarkerView.km_raw,
            AccidentMarkerView.km_accurate,
            AccidentMarkerView.road_segment_id,
            AccidentMarkerView.road_segment_number,
            AccidentMarkerView.road_segment_name,
            AccidentMarkerView.road_segment_from_km,
            AccidentMarkerView.road_segment_to_km,
            AccidentMarkerView.road_segment_length_km,
            AccidentMarkerView.yishuv_symbol.label("accident_yishuv_symbol"),
            AccidentMarkerView.yishuv_name.label("accident_yishuv_name"),
            AccidentMarkerView.geo_area,
            AccidentMarkerView.geo_area_hebrew,
            AccidentMarkerView.day_night,
            AccidentMarkerView.day_night_hebrew,
            AccidentMarkerView.day_in_week,
            AccidentMarkerView.day_in_week_hebrew,
            AccidentMarkerView.traffic_light,
            AccidentMarkerView.traffic_light_hebrew,
            AccidentMarkerView.region.label("accident_region"),
            AccidentMarkerView.region_hebrew.label("accident_region_hebrew"),
            AccidentMarkerView.district.label("accident_district"),
            AccidentMarkerView.district_hebrew.label("accident_district_hebrew"),
            AccidentMarkerView.natural_area.label("accident_natural_area"),
            AccidentMarkerView.natural_area_hebrew.label("accident_natural_area_hebrew"),
            AccidentMarkerView.municipal_status.label("accident_municipal_status"),
            AccidentMarkerView.municipal_status_hebrew.label("accident_municipal_status_hebrew"),
            AccidentMarkerView.yishuv_shape.label("accident_yishuv_shape"),
            AccidentMarkerView.yishuv_shape_hebrew.label("accident_yishuv_shape_hebrew"),
            AccidentMarkerView.street1,
            AccidentMarkerView.street1_hebrew,
            AccidentMarkerView.street2,
            AccidentMarkerView.street2_hebrew,
            AccidentMarkerView.non_urban_intersection,
            AccidentMarkerView.non_urban_intersection_hebrew,
            AccidentMarkerView.non_urban_intersection_by_junction_number,
            AccidentMarkerView.accident_day,
            AccidentMarkerView.accident_hour_raw,
            AccidentMarkerView.accident_hour_raw_hebrew,
            AccidentMarkerView.accident_hour,
            AccidentMarkerView.accident_minute,
            AccidentMarkerView.accident_year,
            AccidentMarkerView.accident_month,
            AccidentMarkerView.geom,
            AccidentMarkerView.longitude,
            AccidentMarkerView.latitude,
            AccidentMarkerView.x,
            AccidentMarkerView.y,
            VehiclesView.id,
            VehiclesView.accident_id,
            VehiclesView.provider_and_id,
            VehiclesView.provider_code,
            VehiclesView.file_type_police,
            VehiclesView.engine_volume,
            VehiclesView.engine_volume_hebrew,
            VehiclesView.manufacturing_year,
            VehiclesView.driving_directions,
            VehiclesView.driving_directions_hebrew,
            VehiclesView.vehicle_status,
            VehiclesView.vehicle_status_hebrew,
            VehiclesView.vehicle_attribution,
            VehiclesView.vehicle_attribution_hebrew,
            VehiclesView.seats,
            VehiclesView.total_weight,
            VehiclesView.total_weight_hebrew,
            VehiclesView.vehicle_type,
            VehiclesView.vehicle_type_hebrew,
            VehiclesView.vehicle_damage,
            VehiclesView.vehicle_damage_hebrew,
            VehiclesView.car_id
        ]
        table = VehiclesView.__table__
        from_clause = table \
            .join(AccidentMarkerView,
                  and_(VehiclesView.provider_code == AccidentMarkerView.provider_code,
                       VehiclesView.accident_id == AccidentMarkerView.id,
                       VehiclesView.accident_year == AccidentMarkerView.accident_year))
        return select(selected_columns) \
            .select_from(from_clause)

VIEWS = Views()
