"""Added road_segments table

Revision ID: 02a8fabf9e53
Revises: 3070e32fe18
Create Date: 2019-05-20 14:25:13.745507

"""

# revision identifiers, used by Alembic.
revision = '02a8fabf9e53'
down_revision = '3070e32fe18'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

table_name = 'road_segments'

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(table_name,
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, primary_key=True),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('road', sa.Integer(), nullable=True),
    sa.Column('segment', sa.Integer(), nullable=True),
    sa.Column('from_km', sa.Float(), nullable=True),
    sa.Column('from_name', sa.Text(), nullable=True),
    sa.Column('to_km', sa.Float(), nullable=True),
    sa.Column('to_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(table_name)
    # ### end Alembic commands ###
