"""Add injured_around_school_all_data

Revision ID: 10ffa15c5d24
Revises: 15d9409816f2
Create Date: 2019-08-22 02:29:04.613196

"""

# revision identifiers, used by Alembic.
revision = '10ffa15c5d24'
down_revision = '15d9409816f2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('injured_around_school_all_data',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('school_id', sa.Float(), nullable=False),
    sa.Column('markers_provider_and_id', sa.BigInteger(), nullable=True),
    sa.Column('markers_provider_code', sa.Float(), nullable=True),
    sa.Column('markers_description', sa.Text(), nullable=True),
    sa.Column('markers_accident_type', sa.Float(), nullable=True),
    sa.Column('markers_accident_severity', sa.Float(), nullable=True),
    sa.Column('markers_address', sa.Text(), nullable=True),
    sa.Column('markers_location_accuracy', sa.Float(), nullable=True),
    sa.Column('markers_road_type', sa.Float(), nullable=True),
    sa.Column('markers_road_shape', sa.Float(), nullable=True),
    sa.Column('markers_day_type', sa.Float(), nullable=True),
    sa.Column('markers_police_unit', sa.Float(), nullable=True),
    sa.Column('markers_mainStreet', sa.Text(), nullable=True),
    sa.Column('markers_secondaryStreet', sa.Text(), nullable=True),
    sa.Column('markers_junction', sa.Text(), nullable=True),
    sa.Column('markers_one_lane', sa.Float(), nullable=True),
    sa.Column('markers_multi_lane', sa.Float(), nullable=True),
    sa.Column('markers_speed_limit', sa.Float(), nullable=True),
    sa.Column('markers_road_intactness', sa.Float(), nullable=True),
    sa.Column('markers_road_width', sa.Float(), nullable=True),
    sa.Column('markers_road_sign', sa.Float(), nullable=True),
    sa.Column('markers_road_light', sa.Float(), nullable=True),
    sa.Column('markers_road_control', sa.Float(), nullable=True),
    sa.Column('markers_weather', sa.Float(), nullable=True),
    sa.Column('markers_road_surface', sa.Float(), nullable=True),
    sa.Column('markers_road_object', sa.Float(), nullable=True),
    sa.Column('markers_object_distance', sa.Float(), nullable=True),
    sa.Column('markers_didnt_cross', sa.Float(), nullable=True),
    sa.Column('markers_cross_mode', sa.Float(), nullable=True),
    sa.Column('markers_cross_location', sa.Float(), nullable=True),
    sa.Column('markers_cross_direction', sa.Float(), nullable=True),
    sa.Column('markers_video_link', sa.Text(), nullable=True),
    sa.Column('markers_road1', sa.Float(), nullable=True),
    sa.Column('markers_road2', sa.Float(), nullable=True),
    sa.Column('markers_km', sa.Float(), nullable=True),
    sa.Column('markers_yishuv_symbol', sa.Float(), nullable=True),
    sa.Column('markers_yishuv_name', sa.Text(), nullable=True),
    sa.Column('markers_geo_area', sa.Float(), nullable=True),
    sa.Column('markers_day_night', sa.Float(), nullable=True),
    sa.Column('markers_day_in_week', sa.Float(), nullable=True),
    sa.Column('markers_traffic_light', sa.Float(), nullable=True),
    sa.Column('markers_region', sa.Float(), nullable=True),
    sa.Column('markers_district', sa.Float(), nullable=True),
    sa.Column('markers_natural_area', sa.Float(), nullable=True),
    sa.Column('markers_municipal_status', sa.Float(), nullable=True),
    sa.Column('markers_yishuv_shape', sa.Float(), nullable=True),
    sa.Column('markers_street1', sa.Float(), nullable=True),
    sa.Column('markers_street1_hebrew', sa.Text(), nullable=True),
    sa.Column('markers_street2', sa.Float(), nullable=True),
    sa.Column('markers_street2_hebrew', sa.Text(), nullable=True),
    sa.Column('markers_home', sa.Float(), nullable=True),
    sa.Column('markers_urban_intersection', sa.Float(), nullable=True),
    sa.Column('markers_non_urban_intersection', sa.Float(), nullable=True),
    sa.Column('markers_non_urban_intersection_hebrew', sa.Text(), nullable=True),
    sa.Column('markers_accident_year', sa.Float(), nullable=True),
    sa.Column('markers_accident_month', sa.Float(), nullable=True),
    sa.Column('markers_accident_day', sa.Float(), nullable=True),
    sa.Column('markers_accident_hour_raw', sa.Float(), nullable=True),
    sa.Column('markers_accident_hour', sa.Float(), nullable=True),
    sa.Column('markers_accident_minute', sa.Float(), nullable=True),
    sa.Column('markers_x', sa.Float(), nullable=True),
    sa.Column('markers_y', sa.Float(), nullable=True),
    sa.Column('markers_vehicle_type_rsa', sa.Text(), nullable=True),
    sa.Column('markers_violation_type_rsa', sa.Text(), nullable=True),
    sa.Column('markers_geom', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.Column('involved_provider_and_id', sa.BigInteger(), nullable=True),
    sa.Column('involved_provider_code', sa.Float(), nullable=True),
    sa.Column('involved_accident_id', sa.BigInteger(), nullable=True),
    sa.Column('involved_involved_type', sa.Float(), nullable=True),
    sa.Column('involved_license_acquiring_date', sa.Float(), nullable=True),
    sa.Column('involved_age_group', sa.Float(), nullable=True),
    sa.Column('involved_sex', sa.Float(), nullable=True),
    sa.Column('involved_vehicle_type', sa.Float(), nullable=True),
    sa.Column('involved_safety_measures', sa.Float(), nullable=True),
    sa.Column('involved_involve_yishuv_symbol', sa.Float(), nullable=True),
    sa.Column('involved_involve_yishuv_name', sa.Text(), nullable=True),
    sa.Column('involved_injury_severity', sa.Float(), nullable=True),
    sa.Column('involved_injured_type', sa.Float(), nullable=True),
    sa.Column('involved_injured_position', sa.Float(), nullable=True),
    sa.Column('involved_population_type', sa.Float(), nullable=True),
    sa.Column('involved_home_region', sa.Float(), nullable=True),
    sa.Column('involved_home_district', sa.Float(), nullable=True),
    sa.Column('involved_home_natural_area', sa.Float(), nullable=True),
    sa.Column('involved_home_municipal_status', sa.Float(), nullable=True),
    sa.Column('involved_home_residence_type', sa.Float(), nullable=True),
    sa.Column('involved_hospital_time', sa.Float(), nullable=True),
    sa.Column('involved_medical_type', sa.Float(), nullable=True),
    sa.Column('involved_release_dest', sa.Float(), nullable=True),
    sa.Column('involved_safety_measures_use', sa.Float(), nullable=True),
    sa.Column('involved_late_deceased', sa.Float(), nullable=True),
    sa.Column('involved_car_id', sa.Float(), nullable=True),
    sa.Column('involved_involve_id', sa.Float(), nullable=True),
    sa.Column('involved_accident_year', sa.Float(), nullable=True),
    sa.Column('involved_accident_month', sa.Float(), nullable=True),
    sa.Column('involved_injury_severity_mais', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_injured_around_school_all_data_id'), 'injured_around_school_all_data', ['id'], unique=False)
    op.create_index(op.f('ix_injured_around_school_all_data_school_id'), 'injured_around_school_all_data', ['school_id'], unique=False)
    op.create_index(op.f('ix_injured_around_school_school_id'), 'injured_around_school', ['school_id'], unique=False)
    op.create_index(op.f('ix_injured_around_school_school_yishuv_name'), 'injured_around_school', ['school_yishuv_name'], unique=False)
    op.create_index(op.f('ix_schools_with_description_municipality_name'), 'schools_with_description', ['municipality_name'], unique=False)
    op.create_index(op.f('ix_schools_with_description_school_id'), 'schools_with_description', ['school_id'], unique=False)
    op.create_index(op.f('ix_schools_with_description_yishuv_name'), 'schools_with_description', ['yishuv_name'], unique=False)
    op.drop_index('idx_schools_with_description_geom', table_name='schools_with_description')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_schools_with_description_geom', 'schools_with_description', ['geom'], unique=False)
    op.drop_index(op.f('ix_schools_with_description_yishuv_name'), table_name='schools_with_description')
    op.drop_index(op.f('ix_schools_with_description_school_id'), table_name='schools_with_description')
    op.drop_index(op.f('ix_schools_with_description_municipality_name'), table_name='schools_with_description')
    op.drop_index(op.f('ix_injured_around_school_school_yishuv_name'), table_name='injured_around_school')
    op.drop_index(op.f('ix_injured_around_school_school_id'), table_name='injured_around_school')
    op.drop_index(op.f('ix_injured_around_school_all_data_school_id'), table_name='injured_around_school_all_data')
    op.drop_index(op.f('ix_injured_around_school_all_data_id'), table_name='injured_around_school_all_data')
    op.drop_table('injured_around_school_all_data')
    ### end Alembic commands ###
