"""Add school_id to locationsubscribers

Revision ID: 131150cfc546
Revises: 4c4b79f8c4a
Create Date: 2019-08-25 04:31:03.913792

"""

# revision identifiers, used by Alembic.
revision = '131150cfc546'
down_revision = '4c4b79f8c4a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    op.add_column('locationsubscribers', sa.Column('school_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locationsubscribers', 'school_id')
    ### end Alembic commands ###
