"""modify injured_around_school table

Revision ID: 15d9409816f2
Revises: faa6ec8d08c
Create Date: 2019-08-21 02:59:18.297851

"""

# revision identifiers, used by Alembic.
revision = '15d9409816f2'
down_revision = 'faa6ec8d08c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('injured_around_school', sa.Column('killed_count', sa.Integer(), nullable=True))
    op.add_column('injured_around_school', sa.Column('light_injured_count', sa.Integer(), nullable=True))
    op.add_column('injured_around_school', sa.Column('rank_in_yishuv', sa.Integer(), nullable=True))
    op.add_column('injured_around_school', sa.Column('severly_injured_count', sa.Integer(), nullable=True))
    op.add_column('injured_around_school', sa.Column('total_injured_killed_count', sa.Integer(), nullable=True))
    op.drop_column('injured_around_school', 'involved_injury_severity')
    op.drop_column('injured_around_school', 'involved_injury_severity_hebrew')
    op.drop_column('injured_around_school', 'injured_count')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('injured_around_school', sa.Column('injured_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('injured_around_school', sa.Column('involved_injury_severity_hebrew', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('injured_around_school', sa.Column('involved_injury_severity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('injured_around_school', 'total_injured_killed_count')
    op.drop_column('injured_around_school', 'severly_injured_count')
    op.drop_column('injured_around_school', 'rank_in_yishuv')
    op.drop_column('injured_around_school', 'light_injured_count')
    op.drop_column('injured_around_school', 'killed_count')
    ### end Alembic commands ###
