"""add_schools_with_description_2020

Revision ID: 16c2d576e01e
Revises: 7c472e4582de
Create Date: 2020-08-16 10:30:23.748793

"""

# revision identifiers, used by Alembic.
revision = '16c2d576e01e'
down_revision = '7c472e4582de'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table('schools_with_description2020',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('school_name', sa.Text(), nullable=True),
    sa.Column('municipality_name', sa.Text(), nullable=True),
    sa.Column('yishuv_name', sa.Text(), nullable=True),
    sa.Column('institution_type', sa.Text(), nullable=True),
    sa.Column('lowest_grade', sa.Text(), nullable=True),
    sa.Column('highest_grade', sa.Text(), nullable=True),
    sa.Column('location_accuracy', sa.Text(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_with_description2020_geom'), 'schools_with_description2020', ['geom'], unique=False)
    op.create_index(op.f('ix_schools_with_description2020_id'), 'schools_with_description2020', ['id'], unique=False)
    op.create_index(op.f('ix_schools_with_description2020_municipality_name'), 'schools_with_description2020', ['municipality_name'], unique=False)
    op.create_index(op.f('ix_schools_with_description2020_school_id'), 'schools_with_description2020', ['school_id'], unique=False)
    op.create_index(op.f('ix_schools_with_description2020_yishuv_name'), 'schools_with_description2020', ['yishuv_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schools_with_description2020_yishuv_name'), table_name='schools_with_description2020')
    op.drop_index(op.f('ix_schools_with_description2020_school_id'), table_name='schools_with_description2020')
    op.drop_index(op.f('ix_schools_with_description2020_municipality_name'), table_name='schools_with_description2020')
    op.drop_index(op.f('ix_schools_with_description2020_id'), table_name='schools_with_description2020')
    op.drop_index(op.f('ix_schools_with_description2020_geom'), table_name='schools_with_description2020')
    op.drop_table('schools_with_description2020')
    # ### end Alembic commands ###
