"""change minizipali_status to municipal_status

Revision ID: 1723862d5c0
Revises: 231f70d55609
Create Date: 2018-10-01 23:58:53.049218

"""

# revision identifiers, used by Alembic.
revision = '1723862d5c0'
down_revision = '231f70d55609'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('municipal_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('municipal_status_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_municipal_status_id'), 'municipal_status', ['id'], unique=False)
    op.drop_table('minizipali_status')
    op.add_column('markers', sa.Column('municipal_status', sa.Integer(), nullable=True))
    op.drop_column('markers', 'minizipali_status')
    op.add_column('markers_no_location', sa.Column('municipal_status', sa.Integer(), nullable=True))
    op.drop_column('markers_no_location', 'minizipali_status')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers_no_location', sa.Column('minizipali_status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('markers_no_location', 'municipal_status')
    op.add_column('markers', sa.Column('minizipali_status', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('markers', 'municipal_status')
    op.create_table('minizipali_status',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('minizipali_status_hebrew', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'minizipali_status_pkey')
    )
    op.drop_index(op.f('ix_municipal_status_id'), table_name='municipal_status')
    op.drop_table('municipal_status')
    ### end Alembic commands ###
