"""change car_type to vehicle_type

Revision ID: 231f70d55609
Revises: 20f14f4f1de7
Create Date: 2018-10-01 23:45:24.503531

"""

# revision identifiers, used by Alembic.
revision = '231f70d55609'
down_revision = '20f14f4f1de7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('involved', sa.Column('vehicle_type', sa.Integer(), nullable=True))
    op.drop_column('involved', 'car_type')
    op.add_column('involved_no_location', sa.Column('vehicle_type', sa.Integer(), nullable=True))
    op.drop_column('involved_no_location', 'car_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('involved_no_location', sa.Column('car_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('involved_no_location', 'vehicle_type')
    op.add_column('involved', sa.Column('car_type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('involved', 'vehicle_type')
    ### end Alembic commands ###
