"""add_video

Revision ID: 24e9d637df99
Revises: 3741581c7fc4
Create Date: 2017-11-05 06:34:23.719230

"""

# revision identifiers, used by Alembic.
revision = '24e9d637df99'
down_revision = '3741581c7fc4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('video', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markers', 'video')
    ### end Alembic commands ###
