"""add road1, road2 and km to markers table

Revision ID: 283bc6a2bcab
Revises: 2f83f4f1b63d
Create Date: 2018-01-19 17:16:44.904000

"""

# revision identifiers, used by Alembic.
revision = '283bc6a2bcab'
down_revision = '2f83f4f1b63d'
branch_labels = None
depends_on = None

import sqlalchemy as sa

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('km', sa.Float(), nullable=True))
    op.add_column('markers', sa.Column('road1', sa.Integer(), nullable=True))
    op.add_column('markers', sa.Column('road2', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markers', 'road2')
    op.drop_column('markers', 'road1')
    op.drop_column('markers', 'km')
    ### end Alembic commands ###
