"""recreate_dictionary_tables

Revision ID: 2cd17a42424b
Revises: 2ae0848d71ea
Create Date: 2018-12-12 10:29:16.390835

"""

# revision identifiers, used by Alembic.
revision = '2cd17a42424b'
down_revision = '2ae0848d71ea'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accident_hour_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('accident_hour_raw_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_accident_hour_raw_id'), 'accident_hour_raw', ['id'], unique=False)
    op.create_index(op.f('ix_accident_hour_raw_provider_code'), 'accident_hour_raw', ['provider_code'], unique=False)
    op.create_index(op.f('ix_accident_hour_raw_year'), 'accident_hour_raw', ['year'], unique=False)
    op.create_table('accident_month',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('accident_month_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_accident_month_id'), 'accident_month', ['id'], unique=False)
    op.create_index(op.f('ix_accident_month_provider_code'), 'accident_month', ['provider_code'], unique=False)
    op.create_index(op.f('ix_accident_month_year'), 'accident_month', ['year'], unique=False)
    op.create_table('accident_severity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('accident_severity_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_accident_severity_id'), 'accident_severity', ['id'], unique=False)
    op.create_index(op.f('ix_accident_severity_provider_code'), 'accident_severity', ['provider_code'], unique=False)
    op.create_index(op.f('ix_accident_severity_year'), 'accident_severity', ['year'], unique=False)
    op.create_table('accident_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('accident_type_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_accident_type_id'), 'accident_type', ['id'], unique=False)
    op.create_index(op.f('ix_accident_type_provider_code'), 'accident_type', ['provider_code'], unique=False)
    op.create_index(op.f('ix_accident_type_year'), 'accident_type', ['year'], unique=False)
    op.create_table('age_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('age_group_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_age_group_id'), 'age_group', ['id'], unique=False)
    op.create_index(op.f('ix_age_group_provider_code'), 'age_group', ['provider_code'], unique=False)
    op.create_index(op.f('ix_age_group_year'), 'age_group', ['year'], unique=False)
    op.create_table('columns_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('column_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_columns_description_id'), 'columns_description', ['id'], unique=False)
    op.create_index(op.f('ix_columns_description_provider_code'), 'columns_description', ['provider_code'], unique=False)
    op.create_index(op.f('ix_columns_description_year'), 'columns_description', ['year'], unique=False)
    op.create_table('cross_direction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('cross_direction_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_cross_direction_id'), 'cross_direction', ['id'], unique=False)
    op.create_index(op.f('ix_cross_direction_provider_code'), 'cross_direction', ['provider_code'], unique=False)
    op.create_index(op.f('ix_cross_direction_year'), 'cross_direction', ['year'], unique=False)
    op.create_table('cross_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('cross_location_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_cross_location_id'), 'cross_location', ['id'], unique=False)
    op.create_index(op.f('ix_cross_location_provider_code'), 'cross_location', ['provider_code'], unique=False)
    op.create_index(op.f('ix_cross_location_year'), 'cross_location', ['year'], unique=False)
    op.create_table('cross_mode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('cross_mode_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_cross_mode_id'), 'cross_mode', ['id'], unique=False)
    op.create_index(op.f('ix_cross_mode_provider_code'), 'cross_mode', ['provider_code'], unique=False)
    op.create_index(op.f('ix_cross_mode_year'), 'cross_mode', ['year'], unique=False)
    op.create_table('day_in_week',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('day_in_week_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_day_in_week_id'), 'day_in_week', ['id'], unique=False)
    op.create_index(op.f('ix_day_in_week_provider_code'), 'day_in_week', ['provider_code'], unique=False)
    op.create_index(op.f('ix_day_in_week_year'), 'day_in_week', ['year'], unique=False)
    op.create_table('day_night',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('day_night_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_day_night_id'), 'day_night', ['id'], unique=False)
    op.create_index(op.f('ix_day_night_provider_code'), 'day_night', ['provider_code'], unique=False)
    op.create_index(op.f('ix_day_night_year'), 'day_night', ['year'], unique=False)
    op.create_table('day_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('day_type_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_day_type_id'), 'day_type', ['id'], unique=False)
    op.create_index(op.f('ix_day_type_provider_code'), 'day_type', ['provider_code'], unique=False)
    op.create_index(op.f('ix_day_type_year'), 'day_type', ['year'], unique=False)
    op.create_table('didnt_cross',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('didnt_cross_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_didnt_cross_id'), 'didnt_cross', ['id'], unique=False)
    op.create_index(op.f('ix_didnt_cross_provider_code'), 'didnt_cross', ['provider_code'], unique=False)
    op.create_index(op.f('ix_didnt_cross_year'), 'didnt_cross', ['year'], unique=False)
    op.create_table('district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('district_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_district_id'), 'district', ['id'], unique=False)
    op.create_index(op.f('ix_district_provider_code'), 'district', ['provider_code'], unique=False)
    op.create_index(op.f('ix_district_year'), 'district', ['year'], unique=False)
    op.create_table('driving_directions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('driving_directions_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_driving_directions_id'), 'driving_directions', ['id'], unique=False)
    op.create_index(op.f('ix_driving_directions_provider_code'), 'driving_directions', ['provider_code'], unique=False)
    op.create_index(op.f('ix_driving_directions_year'), 'driving_directions', ['year'], unique=False)
    op.create_table('engine_volume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('engine_volume_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_engine_volume_id'), 'engine_volume', ['id'], unique=False)
    op.create_index(op.f('ix_engine_volume_provider_code'), 'engine_volume', ['provider_code'], unique=False)
    op.create_index(op.f('ix_engine_volume_year'), 'engine_volume', ['year'], unique=False)
    op.create_table('geo_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('geo_area_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_geo_area_id'), 'geo_area', ['id'], unique=False)
    op.create_index(op.f('ix_geo_area_provider_code'), 'geo_area', ['provider_code'], unique=False)
    op.create_index(op.f('ix_geo_area_year'), 'geo_area', ['year'], unique=False)
    op.create_table('hospital_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('hospital_time_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_hospital_time_id'), 'hospital_time', ['id'], unique=False)
    op.create_index(op.f('ix_hospital_time_provider_code'), 'hospital_time', ['provider_code'], unique=False)
    op.create_index(op.f('ix_hospital_time_year'), 'hospital_time', ['year'], unique=False)
    op.create_table('injured_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('injured_position_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_injured_position_id'), 'injured_position', ['id'], unique=False)
    op.create_index(op.f('ix_injured_position_provider_code'), 'injured_position', ['provider_code'], unique=False)
    op.create_index(op.f('ix_injured_position_year'), 'injured_position', ['year'], unique=False)
    op.create_table('injured_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('injured_type_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_injured_type_id'), 'injured_type', ['id'], unique=False)
    op.create_index(op.f('ix_injured_type_provider_code'), 'injured_type', ['provider_code'], unique=False)
    op.create_index(op.f('ix_injured_type_year'), 'injured_type', ['year'], unique=False)
    op.create_table('injury_severity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('injury_severity_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_injury_severity_id'), 'injury_severity', ['id'], unique=False)
    op.create_index(op.f('ix_injury_severity_provider_code'), 'injury_severity', ['provider_code'], unique=False)
    op.create_index(op.f('ix_injury_severity_year'), 'injury_severity', ['year'], unique=False)
    op.create_table('involved_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('involved_type_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_involved_type_id'), 'involved_type', ['id'], unique=False)
    op.create_index(op.f('ix_involved_type_provider_code'), 'involved_type', ['provider_code'], unique=False)
    op.create_index(op.f('ix_involved_type_year'), 'involved_type', ['year'], unique=False)
    op.create_table('late_deceased',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('late_deceased_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_late_deceased_id'), 'late_deceased', ['id'], unique=False)
    op.create_index(op.f('ix_late_deceased_provider_code'), 'late_deceased', ['provider_code'], unique=False)
    op.create_index(op.f('ix_late_deceased_year'), 'late_deceased', ['year'], unique=False)
    op.create_table('location_accuracy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('location_accuracy_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_location_accuracy_id'), 'location_accuracy', ['id'], unique=False)
    op.create_index(op.f('ix_location_accuracy_provider_code'), 'location_accuracy', ['provider_code'], unique=False)
    op.create_index(op.f('ix_location_accuracy_year'), 'location_accuracy', ['year'], unique=False)
    op.create_table('medical_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('medical_type_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_medical_type_id'), 'medical_type', ['id'], unique=False)
    op.create_index(op.f('ix_medical_type_provider_code'), 'medical_type', ['provider_code'], unique=False)
    op.create_index(op.f('ix_medical_type_year'), 'medical_type', ['year'], unique=False)
    op.create_table('multi_lane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('multi_lane_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_multi_lane_id'), 'multi_lane', ['id'], unique=False)
    op.create_index(op.f('ix_multi_lane_provider_code'), 'multi_lane', ['provider_code'], unique=False)
    op.create_index(op.f('ix_multi_lane_year'), 'multi_lane', ['year'], unique=False)
    op.create_table('municipal_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('municipal_status_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_municipal_status_id'), 'municipal_status', ['id'], unique=False)
    op.create_index(op.f('ix_municipal_status_provider_code'), 'municipal_status', ['provider_code'], unique=False)
    op.create_index(op.f('ix_municipal_status_year'), 'municipal_status', ['year'], unique=False)
    op.create_table('natural_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('natural_area_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_natural_area_id'), 'natural_area', ['id'], unique=False)
    op.create_index(op.f('ix_natural_area_provider_code'), 'natural_area', ['provider_code'], unique=False)
    op.create_index(op.f('ix_natural_area_year'), 'natural_area', ['year'], unique=False)
    op.create_table('object_distance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('object_distance_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_object_distance_id'), 'object_distance', ['id'], unique=False)
    op.create_index(op.f('ix_object_distance_provider_code'), 'object_distance', ['provider_code'], unique=False)
    op.create_index(op.f('ix_object_distance_year'), 'object_distance', ['year'], unique=False)
    op.create_table('one_lane',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('one_lane_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_one_lane_id'), 'one_lane', ['id'], unique=False)
    op.create_index(op.f('ix_one_lane_provider_code'), 'one_lane', ['provider_code'], unique=False)
    op.create_index(op.f('ix_one_lane_year'), 'one_lane', ['year'], unique=False)
    op.create_table('police_unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('police_unit_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_police_unit_id'), 'police_unit', ['id'], unique=False)
    op.create_index(op.f('ix_police_unit_provider_code'), 'police_unit', ['provider_code'], unique=False)
    op.create_index(op.f('ix_police_unit_year'), 'police_unit', ['year'], unique=False)
    op.create_table('population_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('population_type_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_population_type_id'), 'population_type', ['id'], unique=False)
    op.create_index(op.f('ix_population_type_provider_code'), 'population_type', ['provider_code'], unique=False)
    op.create_index(op.f('ix_population_type_year'), 'population_type', ['year'], unique=False)
    op.create_table('provider_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_code_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_code_id'), 'provider_code', ['id'], unique=False)
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('region_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_region_id'), 'region', ['id'], unique=False)
    op.create_index(op.f('ix_region_provider_code'), 'region', ['provider_code'], unique=False)
    op.create_index(op.f('ix_region_year'), 'region', ['year'], unique=False)
    op.create_table('release_dest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('release_dest_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_release_dest_id'), 'release_dest', ['id'], unique=False)
    op.create_index(op.f('ix_release_dest_provider_code'), 'release_dest', ['provider_code'], unique=False)
    op.create_index(op.f('ix_release_dest_year'), 'release_dest', ['year'], unique=False)
    op.create_table('road_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_control_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_road_control_id'), 'road_control', ['id'], unique=False)
    op.create_index(op.f('ix_road_control_provider_code'), 'road_control', ['provider_code'], unique=False)
    op.create_index(op.f('ix_road_control_year'), 'road_control', ['year'], unique=False)
    op.create_table('road_intactness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_intactness_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_road_intactness_id'), 'road_intactness', ['id'], unique=False)
    op.create_index(op.f('ix_road_intactness_provider_code'), 'road_intactness', ['provider_code'], unique=False)
    op.create_index(op.f('ix_road_intactness_year'), 'road_intactness', ['year'], unique=False)
    op.create_table('road_light',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_light_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_road_light_id'), 'road_light', ['id'], unique=False)
    op.create_index(op.f('ix_road_light_provider_code'), 'road_light', ['provider_code'], unique=False)
    op.create_index(op.f('ix_road_light_year'), 'road_light', ['year'], unique=False)
    op.create_table('road_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_object_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_road_object_id'), 'road_object', ['id'], unique=False)
    op.create_index(op.f('ix_road_object_provider_code'), 'road_object', ['provider_code'], unique=False)
    op.create_index(op.f('ix_road_object_year'), 'road_object', ['year'], unique=False)
    op.create_table('road_shape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_shape_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_road_shape_id'), 'road_shape', ['id'], unique=False)
    op.create_index(op.f('ix_road_shape_provider_code'), 'road_shape', ['provider_code'], unique=False)
    op.create_index(op.f('ix_road_shape_year'), 'road_shape', ['year'], unique=False)
    op.create_table('road_sign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_sign_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_road_sign_id'), 'road_sign', ['id'], unique=False)
    op.create_index(op.f('ix_road_sign_provider_code'), 'road_sign', ['provider_code'], unique=False)
    op.create_index(op.f('ix_road_sign_year'), 'road_sign', ['year'], unique=False)
    op.create_table('road_surface',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_surface_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_road_surface_id'), 'road_surface', ['id'], unique=False)
    op.create_index(op.f('ix_road_surface_provider_code'), 'road_surface', ['provider_code'], unique=False)
    op.create_index(op.f('ix_road_surface_year'), 'road_surface', ['year'], unique=False)
    op.create_table('road_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_type_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_road_type_id'), 'road_type', ['id'], unique=False)
    op.create_index(op.f('ix_road_type_provider_code'), 'road_type', ['provider_code'], unique=False)
    op.create_index(op.f('ix_road_type_year'), 'road_type', ['year'], unique=False)
    op.create_table('road_width',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_width_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_road_width_id'), 'road_width', ['id'], unique=False)
    op.create_index(op.f('ix_road_width_provider_code'), 'road_width', ['provider_code'], unique=False)
    op.create_index(op.f('ix_road_width_year'), 'road_width', ['year'], unique=False)
    op.create_table('safety_measures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('safety_measures_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_safety_measures_id'), 'safety_measures', ['id'], unique=False)
    op.create_index(op.f('ix_safety_measures_provider_code'), 'safety_measures', ['provider_code'], unique=False)
    op.create_index(op.f('ix_safety_measures_year'), 'safety_measures', ['year'], unique=False)
    op.create_table('safety_measures_use',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('safety_measures_use_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_safety_measures_use_id'), 'safety_measures_use', ['id'], unique=False)
    op.create_index(op.f('ix_safety_measures_use_provider_code'), 'safety_measures_use', ['provider_code'], unique=False)
    op.create_index(op.f('ix_safety_measures_use_year'), 'safety_measures_use', ['year'], unique=False)
    op.create_table('sex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('sex_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_sex_id'), 'sex', ['id'], unique=False)
    op.create_index(op.f('ix_sex_provider_code'), 'sex', ['provider_code'], unique=False)
    op.create_index(op.f('ix_sex_year'), 'sex', ['year'], unique=False)
    op.create_table('speed_limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('speed_limit_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_speed_limit_id'), 'speed_limit', ['id'], unique=False)
    op.create_index(op.f('ix_speed_limit_provider_code'), 'speed_limit', ['provider_code'], unique=False)
    op.create_index(op.f('ix_speed_limit_year'), 'speed_limit', ['year'], unique=False)
    op.create_table('total_weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('total_weight_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_total_weight_id'), 'total_weight', ['id'], unique=False)
    op.create_index(op.f('ix_total_weight_provider_code'), 'total_weight', ['provider_code'], unique=False)
    op.create_index(op.f('ix_total_weight_year'), 'total_weight', ['year'], unique=False)
    op.create_table('traffic_light',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('traffic_light_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_traffic_light_id'), 'traffic_light', ['id'], unique=False)
    op.create_index(op.f('ix_traffic_light_provider_code'), 'traffic_light', ['provider_code'], unique=False)
    op.create_index(op.f('ix_traffic_light_year'), 'traffic_light', ['year'], unique=False)
    op.create_table('vehicle_attribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('vehicle_attribution_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_vehicle_attribution_id'), 'vehicle_attribution', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_attribution_provider_code'), 'vehicle_attribution', ['provider_code'], unique=False)
    op.create_index(op.f('ix_vehicle_attribution_year'), 'vehicle_attribution', ['year'], unique=False)
    op.create_table('vehicle_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('vehicle_status_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_vehicle_status_id'), 'vehicle_status', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_status_provider_code'), 'vehicle_status', ['provider_code'], unique=False)
    op.create_index(op.f('ix_vehicle_status_year'), 'vehicle_status', ['year'], unique=False)
    op.create_table('vehicle_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('vehicle_type_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_vehicle_type_id'), 'vehicle_type', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_type_provider_code'), 'vehicle_type', ['provider_code'], unique=False)
    op.create_index(op.f('ix_vehicle_type_year'), 'vehicle_type', ['year'], unique=False)
    op.create_table('weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('weather_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_weather_id'), 'weather', ['id'], unique=False)
    op.create_index(op.f('ix_weather_provider_code'), 'weather', ['provider_code'], unique=False)
    op.create_index(op.f('ix_weather_year'), 'weather', ['year'], unique=False)
    op.create_table('yishuv_shape',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('yishuv_shape_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_yishuv_shape_id'), 'yishuv_shape', ['id'], unique=False)
    op.create_index(op.f('ix_yishuv_shape_provider_code'), 'yishuv_shape', ['provider_code'], unique=False)
    op.create_index(op.f('ix_yishuv_shape_year'), 'yishuv_shape', ['year'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yishuv_shape_year'), table_name='yishuv_shape')
    op.drop_index(op.f('ix_yishuv_shape_provider_code'), table_name='yishuv_shape')
    op.drop_index(op.f('ix_yishuv_shape_id'), table_name='yishuv_shape')
    op.drop_table('yishuv_shape')
    op.drop_index(op.f('ix_weather_year'), table_name='weather')
    op.drop_index(op.f('ix_weather_provider_code'), table_name='weather')
    op.drop_index(op.f('ix_weather_id'), table_name='weather')
    op.drop_table('weather')
    op.drop_index(op.f('ix_vehicle_type_year'), table_name='vehicle_type')
    op.drop_index(op.f('ix_vehicle_type_provider_code'), table_name='vehicle_type')
    op.drop_index(op.f('ix_vehicle_type_id'), table_name='vehicle_type')
    op.drop_table('vehicle_type')
    op.drop_index(op.f('ix_vehicle_status_year'), table_name='vehicle_status')
    op.drop_index(op.f('ix_vehicle_status_provider_code'), table_name='vehicle_status')
    op.drop_index(op.f('ix_vehicle_status_id'), table_name='vehicle_status')
    op.drop_table('vehicle_status')
    op.drop_index(op.f('ix_vehicle_attribution_year'), table_name='vehicle_attribution')
    op.drop_index(op.f('ix_vehicle_attribution_provider_code'), table_name='vehicle_attribution')
    op.drop_index(op.f('ix_vehicle_attribution_id'), table_name='vehicle_attribution')
    op.drop_table('vehicle_attribution')
    op.drop_index(op.f('ix_traffic_light_year'), table_name='traffic_light')
    op.drop_index(op.f('ix_traffic_light_provider_code'), table_name='traffic_light')
    op.drop_index(op.f('ix_traffic_light_id'), table_name='traffic_light')
    op.drop_table('traffic_light')
    op.drop_index(op.f('ix_total_weight_year'), table_name='total_weight')
    op.drop_index(op.f('ix_total_weight_provider_code'), table_name='total_weight')
    op.drop_index(op.f('ix_total_weight_id'), table_name='total_weight')
    op.drop_table('total_weight')
    op.drop_index(op.f('ix_speed_limit_year'), table_name='speed_limit')
    op.drop_index(op.f('ix_speed_limit_provider_code'), table_name='speed_limit')
    op.drop_index(op.f('ix_speed_limit_id'), table_name='speed_limit')
    op.drop_table('speed_limit')
    op.drop_index(op.f('ix_sex_year'), table_name='sex')
    op.drop_index(op.f('ix_sex_provider_code'), table_name='sex')
    op.drop_index(op.f('ix_sex_id'), table_name='sex')
    op.drop_table('sex')
    op.drop_index(op.f('ix_safety_measures_use_year'), table_name='safety_measures_use')
    op.drop_index(op.f('ix_safety_measures_use_provider_code'), table_name='safety_measures_use')
    op.drop_index(op.f('ix_safety_measures_use_id'), table_name='safety_measures_use')
    op.drop_table('safety_measures_use')
    op.drop_index(op.f('ix_safety_measures_year'), table_name='safety_measures')
    op.drop_index(op.f('ix_safety_measures_provider_code'), table_name='safety_measures')
    op.drop_index(op.f('ix_safety_measures_id'), table_name='safety_measures')
    op.drop_table('safety_measures')
    op.drop_index(op.f('ix_road_width_year'), table_name='road_width')
    op.drop_index(op.f('ix_road_width_provider_code'), table_name='road_width')
    op.drop_index(op.f('ix_road_width_id'), table_name='road_width')
    op.drop_table('road_width')
    op.drop_index(op.f('ix_road_type_year'), table_name='road_type')
    op.drop_index(op.f('ix_road_type_provider_code'), table_name='road_type')
    op.drop_index(op.f('ix_road_type_id'), table_name='road_type')
    op.drop_table('road_type')
    op.drop_index(op.f('ix_road_surface_year'), table_name='road_surface')
    op.drop_index(op.f('ix_road_surface_provider_code'), table_name='road_surface')
    op.drop_index(op.f('ix_road_surface_id'), table_name='road_surface')
    op.drop_table('road_surface')
    op.drop_index(op.f('ix_road_sign_year'), table_name='road_sign')
    op.drop_index(op.f('ix_road_sign_provider_code'), table_name='road_sign')
    op.drop_index(op.f('ix_road_sign_id'), table_name='road_sign')
    op.drop_table('road_sign')
    op.drop_index(op.f('ix_road_shape_year'), table_name='road_shape')
    op.drop_index(op.f('ix_road_shape_provider_code'), table_name='road_shape')
    op.drop_index(op.f('ix_road_shape_id'), table_name='road_shape')
    op.drop_table('road_shape')
    op.drop_index(op.f('ix_road_object_year'), table_name='road_object')
    op.drop_index(op.f('ix_road_object_provider_code'), table_name='road_object')
    op.drop_index(op.f('ix_road_object_id'), table_name='road_object')
    op.drop_table('road_object')
    op.drop_index(op.f('ix_road_light_year'), table_name='road_light')
    op.drop_index(op.f('ix_road_light_provider_code'), table_name='road_light')
    op.drop_index(op.f('ix_road_light_id'), table_name='road_light')
    op.drop_table('road_light')
    op.drop_index(op.f('ix_road_intactness_year'), table_name='road_intactness')
    op.drop_index(op.f('ix_road_intactness_provider_code'), table_name='road_intactness')
    op.drop_index(op.f('ix_road_intactness_id'), table_name='road_intactness')
    op.drop_table('road_intactness')
    op.drop_index(op.f('ix_road_control_year'), table_name='road_control')
    op.drop_index(op.f('ix_road_control_provider_code'), table_name='road_control')
    op.drop_index(op.f('ix_road_control_id'), table_name='road_control')
    op.drop_table('road_control')
    op.drop_index(op.f('ix_release_dest_year'), table_name='release_dest')
    op.drop_index(op.f('ix_release_dest_provider_code'), table_name='release_dest')
    op.drop_index(op.f('ix_release_dest_id'), table_name='release_dest')
    op.drop_table('release_dest')
    op.drop_index(op.f('ix_region_year'), table_name='region')
    op.drop_index(op.f('ix_region_provider_code'), table_name='region')
    op.drop_index(op.f('ix_region_id'), table_name='region')
    op.drop_table('region')
    op.drop_index(op.f('ix_provider_code_id'), table_name='provider_code')
    op.drop_table('provider_code')
    op.drop_index(op.f('ix_population_type_year'), table_name='population_type')
    op.drop_index(op.f('ix_population_type_provider_code'), table_name='population_type')
    op.drop_index(op.f('ix_population_type_id'), table_name='population_type')
    op.drop_table('population_type')
    op.drop_index(op.f('ix_police_unit_year'), table_name='police_unit')
    op.drop_index(op.f('ix_police_unit_provider_code'), table_name='police_unit')
    op.drop_index(op.f('ix_police_unit_id'), table_name='police_unit')
    op.drop_table('police_unit')
    op.drop_index(op.f('ix_one_lane_year'), table_name='one_lane')
    op.drop_index(op.f('ix_one_lane_provider_code'), table_name='one_lane')
    op.drop_index(op.f('ix_one_lane_id'), table_name='one_lane')
    op.drop_table('one_lane')
    op.drop_index(op.f('ix_object_distance_year'), table_name='object_distance')
    op.drop_index(op.f('ix_object_distance_provider_code'), table_name='object_distance')
    op.drop_index(op.f('ix_object_distance_id'), table_name='object_distance')
    op.drop_table('object_distance')
    op.drop_index(op.f('ix_natural_area_year'), table_name='natural_area')
    op.drop_index(op.f('ix_natural_area_provider_code'), table_name='natural_area')
    op.drop_index(op.f('ix_natural_area_id'), table_name='natural_area')
    op.drop_table('natural_area')
    op.drop_index(op.f('ix_municipal_status_year'), table_name='municipal_status')
    op.drop_index(op.f('ix_municipal_status_provider_code'), table_name='municipal_status')
    op.drop_index(op.f('ix_municipal_status_id'), table_name='municipal_status')
    op.drop_table('municipal_status')
    op.drop_index(op.f('ix_multi_lane_year'), table_name='multi_lane')
    op.drop_index(op.f('ix_multi_lane_provider_code'), table_name='multi_lane')
    op.drop_index(op.f('ix_multi_lane_id'), table_name='multi_lane')
    op.drop_table('multi_lane')
    op.drop_index(op.f('ix_medical_type_year'), table_name='medical_type')
    op.drop_index(op.f('ix_medical_type_provider_code'), table_name='medical_type')
    op.drop_index(op.f('ix_medical_type_id'), table_name='medical_type')
    op.drop_table('medical_type')
    op.drop_index(op.f('ix_location_accuracy_year'), table_name='location_accuracy')
    op.drop_index(op.f('ix_location_accuracy_provider_code'), table_name='location_accuracy')
    op.drop_index(op.f('ix_location_accuracy_id'), table_name='location_accuracy')
    op.drop_table('location_accuracy')
    op.drop_index(op.f('ix_late_deceased_year'), table_name='late_deceased')
    op.drop_index(op.f('ix_late_deceased_provider_code'), table_name='late_deceased')
    op.drop_index(op.f('ix_late_deceased_id'), table_name='late_deceased')
    op.drop_table('late_deceased')
    op.drop_index(op.f('ix_involved_type_year'), table_name='involved_type')
    op.drop_index(op.f('ix_involved_type_provider_code'), table_name='involved_type')
    op.drop_index(op.f('ix_involved_type_id'), table_name='involved_type')
    op.drop_table('involved_type')
    op.drop_index(op.f('ix_injury_severity_year'), table_name='injury_severity')
    op.drop_index(op.f('ix_injury_severity_provider_code'), table_name='injury_severity')
    op.drop_index(op.f('ix_injury_severity_id'), table_name='injury_severity')
    op.drop_table('injury_severity')
    op.drop_index(op.f('ix_injured_type_year'), table_name='injured_type')
    op.drop_index(op.f('ix_injured_type_provider_code'), table_name='injured_type')
    op.drop_index(op.f('ix_injured_type_id'), table_name='injured_type')
    op.drop_table('injured_type')
    op.drop_index(op.f('ix_injured_position_year'), table_name='injured_position')
    op.drop_index(op.f('ix_injured_position_provider_code'), table_name='injured_position')
    op.drop_index(op.f('ix_injured_position_id'), table_name='injured_position')
    op.drop_table('injured_position')
    op.drop_index(op.f('ix_hospital_time_year'), table_name='hospital_time')
    op.drop_index(op.f('ix_hospital_time_provider_code'), table_name='hospital_time')
    op.drop_index(op.f('ix_hospital_time_id'), table_name='hospital_time')
    op.drop_table('hospital_time')
    op.drop_index(op.f('ix_geo_area_year'), table_name='geo_area')
    op.drop_index(op.f('ix_geo_area_provider_code'), table_name='geo_area')
    op.drop_index(op.f('ix_geo_area_id'), table_name='geo_area')
    op.drop_table('geo_area')
    op.drop_index(op.f('ix_engine_volume_year'), table_name='engine_volume')
    op.drop_index(op.f('ix_engine_volume_provider_code'), table_name='engine_volume')
    op.drop_index(op.f('ix_engine_volume_id'), table_name='engine_volume')
    op.drop_table('engine_volume')
    op.drop_index(op.f('ix_driving_directions_year'), table_name='driving_directions')
    op.drop_index(op.f('ix_driving_directions_provider_code'), table_name='driving_directions')
    op.drop_index(op.f('ix_driving_directions_id'), table_name='driving_directions')
    op.drop_table('driving_directions')
    op.drop_index(op.f('ix_district_year'), table_name='district')
    op.drop_index(op.f('ix_district_provider_code'), table_name='district')
    op.drop_index(op.f('ix_district_id'), table_name='district')
    op.drop_table('district')
    op.drop_index(op.f('ix_didnt_cross_year'), table_name='didnt_cross')
    op.drop_index(op.f('ix_didnt_cross_provider_code'), table_name='didnt_cross')
    op.drop_index(op.f('ix_didnt_cross_id'), table_name='didnt_cross')
    op.drop_table('didnt_cross')
    op.drop_index(op.f('ix_day_type_year'), table_name='day_type')
    op.drop_index(op.f('ix_day_type_provider_code'), table_name='day_type')
    op.drop_index(op.f('ix_day_type_id'), table_name='day_type')
    op.drop_table('day_type')
    op.drop_index(op.f('ix_day_night_year'), table_name='day_night')
    op.drop_index(op.f('ix_day_night_provider_code'), table_name='day_night')
    op.drop_index(op.f('ix_day_night_id'), table_name='day_night')
    op.drop_table('day_night')
    op.drop_index(op.f('ix_day_in_week_year'), table_name='day_in_week')
    op.drop_index(op.f('ix_day_in_week_provider_code'), table_name='day_in_week')
    op.drop_index(op.f('ix_day_in_week_id'), table_name='day_in_week')
    op.drop_table('day_in_week')
    op.drop_index(op.f('ix_cross_mode_year'), table_name='cross_mode')
    op.drop_index(op.f('ix_cross_mode_provider_code'), table_name='cross_mode')
    op.drop_index(op.f('ix_cross_mode_id'), table_name='cross_mode')
    op.drop_table('cross_mode')
    op.drop_index(op.f('ix_cross_location_year'), table_name='cross_location')
    op.drop_index(op.f('ix_cross_location_provider_code'), table_name='cross_location')
    op.drop_index(op.f('ix_cross_location_id'), table_name='cross_location')
    op.drop_table('cross_location')
    op.drop_index(op.f('ix_cross_direction_year'), table_name='cross_direction')
    op.drop_index(op.f('ix_cross_direction_provider_code'), table_name='cross_direction')
    op.drop_index(op.f('ix_cross_direction_id'), table_name='cross_direction')
    op.drop_table('cross_direction')
    op.drop_index(op.f('ix_columns_description_year'), table_name='columns_description')
    op.drop_index(op.f('ix_columns_description_provider_code'), table_name='columns_description')
    op.drop_index(op.f('ix_columns_description_id'), table_name='columns_description')
    op.drop_table('columns_description')
    op.drop_index(op.f('ix_age_group_year'), table_name='age_group')
    op.drop_index(op.f('ix_age_group_provider_code'), table_name='age_group')
    op.drop_index(op.f('ix_age_group_id'), table_name='age_group')
    op.drop_table('age_group')
    op.drop_index(op.f('ix_accident_type_year'), table_name='accident_type')
    op.drop_index(op.f('ix_accident_type_provider_code'), table_name='accident_type')
    op.drop_index(op.f('ix_accident_type_id'), table_name='accident_type')
    op.drop_table('accident_type')
    op.drop_index(op.f('ix_accident_severity_year'), table_name='accident_severity')
    op.drop_index(op.f('ix_accident_severity_provider_code'), table_name='accident_severity')
    op.drop_index(op.f('ix_accident_severity_id'), table_name='accident_severity')
    op.drop_table('accident_severity')
    op.drop_index(op.f('ix_accident_month_year'), table_name='accident_month')
    op.drop_index(op.f('ix_accident_month_provider_code'), table_name='accident_month')
    op.drop_index(op.f('ix_accident_month_id'), table_name='accident_month')
    op.drop_table('accident_month')
    op.drop_index(op.f('ix_accident_hour_raw_year'), table_name='accident_hour_raw')
    op.drop_index(op.f('ix_accident_hour_raw_provider_code'), table_name='accident_hour_raw')
    op.drop_index(op.f('ix_accident_hour_raw_id'), table_name='accident_hour_raw')
    op.drop_table('accident_hour_raw')
    ### end Alembic commands ###
