"""road_segments_cache

Revision ID: 2dcc57ee1757
Revises: 312c9eb92e40
Create Date: 2021-10-06 06:15:46.663604

"""

# revision identifiers, used by Alembic.
revision = '2dcc57ee1757'
down_revision = '312c9eb92e40'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infographics_road_segments_data_cache',
    sa.Column('road_segment_id', sa.BigInteger(), nullable=False),
    sa.Column('years_ago', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('road_segment_id', 'years_ago')
    )
    op.create_index('infographics_data_road_segments_cache_road_segment_id_years_idx', 'infographics_road_segments_data_cache', ['road_segment_id', 'years_ago'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('infographics_data_road_segments_cache_road_segment_id_years_idx', table_name='infographics_road_segments_data_cache')
    op.drop_table('infographics_road_segments_data_cache')
    # ### end Alembic commands ###
