"""add cbs_locations table

Revision ID: 312c9eb92e40
Revises: bd67c88713b8
Create Date: 2021-08-20 15:46:37.063756

"""

# revision identifiers, used by Alembic.
revision = '312c9eb92e40'
down_revision = 'bd67c88713b8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cbs_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('road1', sa.Integer(), nullable=True),
    sa.Column('road2', sa.Integer(), nullable=True),
    sa.Column('non_urban_intersection_hebrew', sa.Text(), nullable=True),
    sa.Column('yishuv_name', sa.Text(), nullable=True),
    sa.Column('street1_hebrew', sa.Text(), nullable=True),
    sa.Column('street2_hebrew', sa.Text(), nullable=True),
    sa.Column('district_hebrew', sa.Text(), nullable=True),
    sa.Column('region_hebrew', sa.Text(), nullable=True),
    sa.Column('road_segment_name', sa.Text(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    conn = op.get_bind()
    conn.execute("""INSERT INTO cbs_locations 
                        (SELECT ROW_NUMBER() OVER (ORDER BY road1) as id, LOCATIONS.*
                        FROM 
                        (SELECT DISTINCT road1,
                            road2,
                            non_urban_intersection_hebrew,
                            yishuv_name,
                            street1_hebrew,
                            street2_hebrew,
                            district_hebrew,
                            region_hebrew,
                            road_segment_name,
                            longitude,
                            latitude
                        FROM markers_hebrew
                        WHERE (provider_code=1
                               OR provider_code=3)
                          AND (longitude is not null
                               AND latitude is not null)) LOCATIONS)""")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cbs_locations')
    # ### end Alembic commands ###
