"""Add new dictionary tables

Revision ID: 333a785776cd
Revises: b7c8d9e0f1a2
Create Date: 2026-02-02 17:47:20.438985

"""

# revision identifiers, used by Alembic.
revision = '333a785776cd'
down_revision = 'b7c8d9e0f1a2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrance_exit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('entrance_exit_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_entrance_exit_id'), 'entrance_exit', ['id'], unique=False)
    op.create_index(op.f('ix_entrance_exit_provider_code'), 'entrance_exit', ['provider_code'], unique=False)
    op.create_index(op.f('ix_entrance_exit_year'), 'entrance_exit', ['year'], unique=False)
    op.create_table('infrastructure_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('infrastructure_type_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_infrastructure_type_id'), 'infrastructure_type', ['id'], unique=False)
    op.create_index(op.f('ix_infrastructure_type_provider_code'), 'infrastructure_type', ['provider_code'], unique=False)
    op.create_index(op.f('ix_infrastructure_type_year'), 'infrastructure_type', ['year'], unique=False)
    op.create_table('road_alignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_alignment_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_road_alignment_id'), 'road_alignment', ['id'], unique=False)
    op.create_index(op.f('ix_road_alignment_provider_code'), 'road_alignment', ['provider_code'], unique=False)
    op.create_index(op.f('ix_road_alignment_year'), 'road_alignment', ['year'], unique=False)
    op.create_table('road_geometry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('road_geometry_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_road_geometry_id'), 'road_geometry', ['id'], unique=False)
    op.create_index(op.f('ix_road_geometry_provider_code'), 'road_geometry', ['provider_code'], unique=False)
    op.create_index(op.f('ix_road_geometry_year'), 'road_geometry', ['year'], unique=False)
    op.create_table('vehicle_purpose',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('vehicle_purpose_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_vehicle_purpose_id'), 'vehicle_purpose', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_purpose_provider_code'), 'vehicle_purpose', ['provider_code'], unique=False)
    op.create_index(op.f('ix_vehicle_purpose_year'), 'vehicle_purpose', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_purpose_year'), table_name='vehicle_purpose')
    op.drop_index(op.f('ix_vehicle_purpose_provider_code'), table_name='vehicle_purpose')
    op.drop_index(op.f('ix_vehicle_purpose_id'), table_name='vehicle_purpose')
    op.drop_table('vehicle_purpose')
    op.drop_index(op.f('ix_road_geometry_year'), table_name='road_geometry')
    op.drop_index(op.f('ix_road_geometry_provider_code'), table_name='road_geometry')
    op.drop_index(op.f('ix_road_geometry_id'), table_name='road_geometry')
    op.drop_table('road_geometry')
    op.drop_index(op.f('ix_road_alignment_year'), table_name='road_alignment')
    op.drop_index(op.f('ix_road_alignment_provider_code'), table_name='road_alignment')
    op.drop_index(op.f('ix_road_alignment_id'), table_name='road_alignment')
    op.drop_table('road_alignment')
    op.drop_index(op.f('ix_infrastructure_type_year'), table_name='infrastructure_type')
    op.drop_index(op.f('ix_infrastructure_type_provider_code'), table_name='infrastructure_type')
    op.drop_index(op.f('ix_infrastructure_type_id'), table_name='infrastructure_type')
    op.drop_table('infrastructure_type')
    op.drop_index(op.f('ix_entrance_exit_year'), table_name='entrance_exit')
    op.drop_index(op.f('ix_entrance_exit_provider_code'), table_name='entrance_exit')
    op.drop_index(op.f('ix_entrance_exit_id'), table_name='entrance_exit')
    op.drop_table('entrance_exit')
    # ### end Alembic commands ###
