"""tables_additions_field_modifications

Revision ID: 3680a8998648
Revises: 41aa96fd6464
Create Date: 2018-07-17 01:57:41.128223

"""

# revision identifiers, used by Alembic.
revision = '3680a8998648'
down_revision = '41aa96fd6464'
branch_labels = None
depends_on = None

import sqlalchemy as sa

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markers_no_location',
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.Column('type', sa.Integer(), nullable=True),
                    sa.Column('title', sa.String(length=100), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=True),
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('provider_and_id', sa.BigInteger(), nullable=True),
                    sa.Column('provider_code', sa.Integer(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('subtype', sa.Integer(), nullable=True),
                    sa.Column('severity', sa.Integer(), nullable=True),
                    sa.Column('address', sa.Text(), nullable=True),
                    sa.Column('locationAccuracy', sa.Integer(), nullable=True),
                    sa.Column('roadType', sa.Integer(), nullable=True),
                    sa.Column('roadShape', sa.Integer(), nullable=True),
                    sa.Column('dayType', sa.Integer(), nullable=True),
                    sa.Column('unit', sa.Integer(), nullable=True),
                    sa.Column('mainStreet', sa.Text(), nullable=True),
                    sa.Column('secondaryStreet', sa.Text(), nullable=True),
                    sa.Column('junction', sa.Text(), nullable=True),
                    sa.Column('one_lane', sa.Integer(), nullable=True),
                    sa.Column('multi_lane', sa.Integer(), nullable=True),
                    sa.Column('speed_limit', sa.Integer(), nullable=True),
                    sa.Column('intactness', sa.Integer(), nullable=True),
                    sa.Column('road_width', sa.Integer(), nullable=True),
                    sa.Column('road_sign', sa.Integer(), nullable=True),
                    sa.Column('road_light', sa.Integer(), nullable=True),
                    sa.Column('road_control', sa.Integer(), nullable=True),
                    sa.Column('weather', sa.Integer(), nullable=True),
                    sa.Column('road_surface', sa.Integer(), nullable=True),
                    sa.Column('road_object', sa.Integer(), nullable=True),
                    sa.Column('object_distance', sa.Integer(), nullable=True),
                    sa.Column('didnt_cross', sa.Integer(), nullable=True),
                    sa.Column('cross_mode', sa.Integer(), nullable=True),
                    sa.Column('cross_location', sa.Integer(), nullable=True),
                    sa.Column('cross_direction', sa.Integer(), nullable=True),
                    sa.Column('video_link', sa.Text(), nullable=True),
                    sa.Column('road1', sa.Integer(), nullable=True),
                    sa.Column('road2', sa.Integer(), nullable=True),
                    sa.Column('km', sa.Float(), nullable=True),
                    sa.Column('yishuv_symbol', sa.Integer(), nullable=True),
                    sa.Column('geo_area', sa.Integer(), nullable=True),
                    sa.Column('day_night', sa.Integer(), nullable=True),
                    sa.Column('day_in_week', sa.Integer(), nullable=True),
                    sa.Column('traffic_light', sa.Integer(), nullable=True),
                    sa.Column('region', sa.Integer(), nullable=True),
                    sa.Column('district', sa.Integer(), nullable=True),
                    sa.Column('natural_area', sa.Integer(), nullable=True),
                    sa.Column('minizipali_status', sa.Integer(), nullable=True),
                    sa.Column('yishuv_shape', sa.Integer(), nullable=True),
                    sa.Column('street1', sa.Integer(), nullable=True),
                    sa.Column('street2', sa.Integer(), nullable=True),
                    sa.Column('home', sa.Integer(), nullable=True),
                    sa.Column('urban_intersection', sa.Integer(), nullable=True),
                    sa.Column('non_urban_intersection', sa.Integer(), nullable=True),
                    sa.Column('accident_year', sa.Integer(), nullable=True),
                    sa.Column('accident_month', sa.Integer(), nullable=True),
                    sa.Column('accident_day', sa.Integer(), nullable=True),
                    sa.Column('accident_hour_raw', sa.Integer(), nullable=True),
                    sa.Column('accident_hour', sa.Integer(), nullable=True),
                    sa.Column('accident_minute', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id', 'provider_code')
                    )
    op.create_index('id_idx_markers_no_location', 'markers_no_location', ['id'], unique=False)
    op.create_index(op.f('ix_markers_no_location_created'), 'markers_no_location', ['created'], unique=False)
    op.create_index('provider_and_id_idx_markers_no_location', 'markers_no_location', ['provider_and_id'], unique=True)
    op.create_table('involved_no_location',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('provider_and_id', sa.BigInteger(), nullable=True),
                    sa.Column('provider_code', sa.Integer(), nullable=True),
                    sa.Column('accident_id', sa.BigInteger(), nullable=True),
                    sa.Column('involved_type', sa.Integer(), nullable=True),
                    sa.Column('license_acquiring_date', sa.Integer(), nullable=True),
                    sa.Column('age_group', sa.Integer(), nullable=True),
                    sa.Column('sex', sa.Integer(), nullable=True),
                    sa.Column('car_type', sa.Integer(), nullable=True),
                    sa.Column('safety_measures', sa.Integer(), nullable=True),
                    sa.Column('involve_yishuv_symbol', sa.Integer(), nullable=True),
                    sa.Column('injury_severity', sa.Integer(), nullable=True),
                    sa.Column('injured_type', sa.Integer(), nullable=True),
                    sa.Column('injured_position', sa.Integer(), nullable=True),
                    sa.Column('population_type', sa.Integer(), nullable=True),
                    sa.Column('home_region', sa.Integer(), nullable=True),
                    sa.Column('home_district', sa.Integer(), nullable=True),
                    sa.Column('home_natural_area', sa.Integer(), nullable=True),
                    sa.Column('home_municipal_status', sa.Integer(), nullable=True),
                    sa.Column('home_residence_type', sa.Integer(), nullable=True),
                    sa.Column('hospital_time', sa.Integer(), nullable=True),
                    sa.Column('medical_type', sa.Integer(), nullable=True),
                    sa.Column('release_dest', sa.Integer(), nullable=True),
                    sa.Column('safety_measures_use', sa.Integer(), nullable=True),
                    sa.Column('late_deceased', sa.Integer(), nullable=True),
                    sa.Column('car_id', sa.Integer(), nullable=True),
                    sa.Column('involve_id', sa.Integer(), nullable=True),
                    sa.Column('accident_year', sa.Integer(), nullable=True),
                    sa.Column('accident_month', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['accident_id', 'provider_code'],
                                            [u'markers_no_location.id', u'markers_no_location.provider_code'],
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('accident_id_idx_involved_no_location', 'involved_no_location', ['accident_id'], unique=False)
    op.create_index('provider_and_id_idx_involved_no_location', 'involved_no_location', ['provider_and_id'],
                    unique=False)
    op.create_table('vehicles_no_location',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('provider_and_id', sa.BigInteger(), nullable=True),
                    sa.Column('provider_code', sa.Integer(), nullable=True),
                    sa.Column('accident_id', sa.BigInteger(), nullable=True),
                    sa.Column('engine_volume', sa.Integer(), nullable=True),
                    sa.Column('manufacturing_year', sa.Integer(), nullable=True),
                    sa.Column('driving_directions', sa.Integer(), nullable=True),
                    sa.Column('vehicle_status', sa.Integer(), nullable=True),
                    sa.Column('vehicle_attribution', sa.Integer(), nullable=True),
                    sa.Column('vehicle_type', sa.Integer(), nullable=True),
                    sa.Column('seats', sa.Integer(), nullable=True),
                    sa.Column('total_weight', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['accident_id', 'provider_code'],
                                            [u'markers_no_location.id', u'markers_no_location.provider_code'],
                                            ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('accident_id_idx_vehicles_no_location', 'vehicles_no_location', ['accident_id'], unique=False)
    op.create_index('provider_and_id_idx_vehicles_no_location', 'vehicles_no_location', ['provider_and_id'],
                    unique=False)
    op.add_column(u'involved', sa.Column('accident_month', sa.Integer(), nullable=True))
    op.add_column(u'involved', sa.Column('accident_year', sa.Integer(), nullable=True))
    op.add_column(u'involved', sa.Column('car_id', sa.Integer(), nullable=True))
    op.add_column(u'involved', sa.Column('home_natural_area', sa.Integer(), nullable=True))
    op.add_column(u'involved', sa.Column('home_region', sa.Integer(), nullable=True))
    op.add_column(u'involved', sa.Column('involve_id', sa.Integer(), nullable=True))
    op.add_column(u'involved', sa.Column('involve_yishuv_symbol', sa.Integer(), nullable=True))
    op.add_column(u'involved', sa.Column('provider_and_id', sa.BigInteger(), nullable=True))
    op.create_index('provider_and_id_idx_involved', 'involved', ['provider_and_id'], unique=False)
    op.drop_column(u'involved', 'home_area')
    op.drop_column(u'involved', 'home_city')
    op.drop_column(u'involved', 'home_nafa')
    op.add_column(u'markers', sa.Column('accident_day', sa.Integer(), nullable=True))
    op.add_column(u'markers', sa.Column('accident_hour', sa.Integer(), nullable=True))
    op.add_column(u'markers', sa.Column('accident_hour_raw', sa.Integer(), nullable=True))
    op.add_column(u'markers', sa.Column('accident_minute', sa.Integer(), nullable=True))
    op.add_column(u'markers', sa.Column('accident_month', sa.Integer(), nullable=True))
    op.add_column(u'markers', sa.Column('accident_year', sa.Integer(), nullable=True))
    op.add_column(u'markers', sa.Column('home', sa.Integer(), nullable=True))
    op.add_column(u'markers', sa.Column('non_urban_intersection', sa.Integer(), nullable=True))
    op.add_column(u'markers', sa.Column('provider_and_id', sa.BigInteger(), nullable=True))
    op.add_column(u'markers', sa.Column('street1', sa.Integer(), nullable=True))
    op.add_column(u'markers', sa.Column('street2', sa.Integer(), nullable=True))
    op.add_column(u'markers', sa.Column('urban_intersection', sa.Integer(), nullable=True))
    op.create_index('provider_and_id_idx_markers', 'markers', ['provider_and_id'], unique=True)
    op.drop_index('id_idx_markers', table_name='markers')
    op.create_index('id_idx_markers', 'markers', ['id'], unique=False)
    op.add_column(u'vehicles', sa.Column('provider_and_id', sa.BigInteger(), nullable=True))
    op.create_index('provider_and_id_idx_vehicles', 'vehicles', ['provider_and_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('provider_and_id_idx_vehicles', table_name='vehicles')
    op.drop_column(u'vehicles', 'provider_and_id')
    op.drop_index('id_idx_markers', table_name='markers')
    op.create_index('id_idx_markers', 'markers', ['id'], unique=True)
    op.drop_index('provider_and_id_idx_markers', table_name='markers')
    op.drop_column(u'markers', 'urban_intersection')
    op.drop_column(u'markers', 'street2')
    op.drop_column(u'markers', 'street1')
    op.drop_column(u'markers', 'provider_and_id')
    op.drop_column(u'markers', 'non_urban_intersection')
    op.drop_column(u'markers', 'home')
    op.drop_column(u'markers', 'accident_year')
    op.drop_column(u'markers', 'accident_month')
    op.drop_column(u'markers', 'accident_minute')
    op.drop_column(u'markers', 'accident_hour_raw')
    op.drop_column(u'markers', 'accident_hour')
    op.drop_column(u'markers', 'accident_day')
    op.add_column(u'involved', sa.Column('home_nafa', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'involved', sa.Column('home_city', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column(u'involved', sa.Column('home_area', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index('provider_and_id_idx_involved', table_name='involved')
    op.drop_column(u'involved', 'provider_and_id')
    op.drop_column(u'involved', 'involve_yishuv_symbol')
    op.drop_column(u'involved', 'involve_id')
    op.drop_column(u'involved', 'home_region')
    op.drop_column(u'involved', 'home_natural_area')
    op.drop_column(u'involved', 'car_id')
    op.drop_column(u'involved', 'accident_year')
    op.drop_column(u'involved', 'accident_month')
    op.drop_index('provider_and_id_idx_vehicles_no_location', table_name='vehicles_no_location')
    op.drop_index('accident_id_idx_vehicles_no_location', table_name='vehicles_no_location')
    op.drop_table('vehicles_no_location')
    op.drop_index('provider_and_id_idx_involved_no_location', table_name='involved_no_location')
    op.drop_index('accident_id_idx_involved_no_location', table_name='involved_no_location')
    op.drop_table('involved_no_location')
    op.drop_index('provider_and_id_idx_markers_no_location', table_name='markers_no_location')
    op.drop_index(op.f('ix_markers_no_location_created'), table_name='markers_no_location')
    op.drop_index('id_idx_markers_no_location', table_name='markers_no_location')
    op.drop_table('markers_no_location')
    ### end Alembic commands ###
