"""add_vehicle_damage_and_mais_injury_severity

Revision ID: 38b40c62043c
Revises: 3c8ad66233c0
Create Date: 2019-01-19 20:08:15.044765

"""

# revision identifiers, used by Alembic.
revision = '38b40c62043c'
down_revision = '3c8ad66233c0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('injury_severity_mais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('injury_severity_mais_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_injury_severity_mais_id'), 'injury_severity_mais', ['id'], unique=False)
    op.create_index(op.f('ix_injury_severity_mais_provider_code'), 'injury_severity_mais', ['provider_code'], unique=False)
    op.create_index(op.f('ix_injury_severity_mais_year'), 'injury_severity_mais', ['year'], unique=False)

    op.create_table('vehicle_damage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('provider_code', sa.Integer(), nullable=False),
    sa.Column('vehicle_damage_hebrew', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'year', 'provider_code')
    )
    op.create_index(op.f('ix_vehicle_damage_id'), 'vehicle_damage', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_damage_provider_code'), 'vehicle_damage', ['provider_code'], unique=False)
    op.create_index(op.f('ix_vehicle_damage_year'), 'vehicle_damage', ['year'], unique=False)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_vehicle_damage_year'), table_name='vehicle_damage')
    op.drop_index(op.f('ix_vehicle_damage_provider_code'), table_name='vehicle_damage')
    op.drop_index(op.f('ix_vehicle_damage_id'), table_name='vehicle_damage')
    op.drop_table('vehicle_damage')
    op.drop_index(op.f('ix_injury_severity_mais_year'), table_name='injury_severity_mais')
    op.drop_index(op.f('ix_injury_severity_mais_provider_code'), table_name='injury_severity_mais')
    op.drop_index(op.f('ix_injury_severity_mais_id'), table_name='injury_severity_mais')
    op.drop_table('injury_severity_mais')
    ### end Alembic commands ###
