"""add_missing_fields_to_vehicles

Revision ID: 3c8ad66233c0
Revises: 2cd17a42424b
Create Date: 2018-12-17 17:38:28.417292

"""

# revision identifiers, used by Alembic.
revision = '3c8ad66233c0'
down_revision = '2cd17a42424b'
branch_labels = None
depends_on = None

import sqlalchemy as sa

from alembic import op


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('accident_month', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('accident_year', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('car_id', sa.Integer(), nullable=True))
    op.add_column('vehicles_no_location', sa.Column('accident_month', sa.Integer(), nullable=True))
    op.add_column('vehicles_no_location', sa.Column('accident_year', sa.Integer(), nullable=True))
    op.add_column('vehicles_no_location', sa.Column('car_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles_no_location', 'car_id')
    op.drop_column('vehicles_no_location', 'accident_year')
    op.drop_column('vehicles_no_location', 'accident_month')
    op.drop_column('vehicles', 'car_id')
    op.drop_column('vehicles', 'accident_year')
    op.drop_column('vehicles', 'accident_month')
    ### end Alembic commands ###
