"""add cbs fields

Revision ID: 3f07363021f6
Revises: 514e03c883e0
Create Date: 2019-10-19 19:32:28.309116

"""

# revision identifiers, used by Alembic.
revision = '3f07363021f6'
down_revision = '514e03c883e0'
branch_labels = None
depends_on = None

import sqlalchemy as sa

from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('km_accurate', sa.Boolean(), nullable=True))
    op.add_column('markers', sa.Column('km_raw', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markers', 'km_raw')
    op.drop_column('markers', 'km_accurate')
    # ### end Alembic commands ###
