"""Add fields to news flash table

Revision ID: 4f1a251e37d1
Revises: e52b43330abc
Create Date: 2019-10-28 18:11:23.319215

"""

# revision identifiers, used by Alembic.
revision = '4f1a251e37d1'
down_revision = 'e52b43330abc'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_flash', sa.Column('geo_extracted_address', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('geo_extracted_city', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('geo_extracted_district', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('geo_extracted_intersection', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('geo_extracted_road_no', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('geo_extracted_street', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('resolution', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('street2', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_flash', 'street2')
    op.drop_column('news_flash', 'resolution')
    op.drop_column('news_flash', 'geo_extracted_street')
    op.drop_column('news_flash', 'geo_extracted_road_no')
    op.drop_column('news_flash', 'geo_extracted_intersection')
    op.drop_column('news_flash', 'geo_extracted_district')
    op.drop_column('news_flash', 'geo_extracted_city')
    op.drop_column('news_flash', 'geo_extracted_address')
    # ### end Alembic commands ###
