"""modify news_flash table

Revision ID: 550a47a98675
Revises: 35b556aef8ef
Create Date: 2019-03-18 22:23:32.014853

"""

# revision identifiers, used by Alembic.
revision = '550a47a98675'
down_revision = '35b556aef8ef'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_flash', sa.Column('city', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('intersection', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('road1', sa.Float(), nullable=True))
    op.add_column('news_flash', sa.Column('road2', sa.Float(), nullable=True))
    op.add_column('news_flash', sa.Column('street', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_flash', 'street')
    op.drop_column('news_flash', 'road2')
    op.drop_column('news_flash', 'road1')
    op.drop_column('news_flash', 'intersection')
    op.drop_column('news_flash', 'city')
    ### end Alembic commands ###
