"""add_locationsubscribers_table

Revision ID: 56b95d5826c
Revises: 5ac16eaf11a
Create Date: 2018-08-22 19:39:53.613430

"""

# revision identifiers, used by Alembic.
revision = '56b95d5826c'
down_revision = '5ac16eaf11a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locationsubscribers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('ne_lng', sa.Float(), nullable=True),
    sa.Column('ne_lat', sa.Float(), nullable=True),
    sa.Column('sw_lng', sa.Float(), nullable=True),
    sa.Column('sw_lat', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locationsubscribers')
    ### end Alembic commands ###
