"""add file_type_police fields

Revision ID: 59ed13585934
Revises: 960a2171037b
Create Date: 2019-10-18 20:20:02.287916

"""

# revision identifiers, used by Alembic.
revision = '59ed13585934'
down_revision = '960a2171037b'
branch_labels = None
depends_on = None

import sqlalchemy as sa

from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('involved', sa.Column('file_type_police', sa.Integer(), nullable=True))
    op.add_column('markers', sa.Column('file_type_police', sa.Integer(), nullable=True))
    op.add_column('vehicles', sa.Column('file_type_police', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'file_type_police')
    op.drop_column('markers', 'file_type_police')
    op.drop_column('involved', 'file_type_police')
    # ### end Alembic commands ###
