"""schools_table

Revision ID: 5ac16eaf11a
Revises: 3680a8998648
Create Date: 2018-07-21 18:40:32.562699

"""

# revision identifiers, used by Alembic.
revision = '5ac16eaf11a'
down_revision = '3680a8998648'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('fcode_type', sa.Integer(), nullable=True),
    sa.Column('yishuv_symbol', sa.Integer(), nullable=True),
    sa.Column('yishuv_name', sa.Text(), nullable=True),
    sa.Column('school_name', sa.Text(), nullable=True),
    sa.Column('school_latin_name', sa.Text(), nullable=True),
    sa.Column('usg', sa.Integer(), nullable=True),
    sa.Column('usg_code', sa.Integer(), nullable=True),
    sa.Column('e_ord', sa.Float(), nullable=True),
    sa.Column('n_ord', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326), nullable=True),
    sa.Column('data_year', sa.Integer(), nullable=True),
    sa.Column('prdct_ver', sa.DateTime(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_geom'), 'schools', ['geom'], unique=False)
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.create_index(op.f('ix_schools_yishuv_symbol'), 'schools', ['yishuv_symbol'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schools_yishuv_symbol'), table_name='schools')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_index(op.f('ix_schools_geom'), table_name='schools')
    op.drop_table('schools')
    ### end Alembic commands ###
