"""Added default date to comment

Revision ID: 664f8a93794e
Revises: ca69b2327f42
Create Date: 2023-08-17 13:29:22.481827

"""

# revision identifiers, used by Alembic.
revision = '664f8a93794e'
down_revision = 'ca69b2327f42'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'created_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'created_time',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
  
    # ### end Alembic commands ###
