"""Added newsflash features

Revision ID: 786584a43a32
Revises: 10023013f155
Create Date: 2021-02-24 21:00:01.883726

"""

# revision identifiers, used by Alembic.
revision = '786584a43a32'
down_revision = '10023013f155'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'news_flash', ['id'])
    op.create_table('newsflash_features',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('newsflash_id', sa.BigInteger(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('is_urban', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['newsflash_id'], ['news_flash.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsflash_features')
    op.drop_constraint(None, 'news_flash', type_='unique')
    # ### end Alembic commands ###
