"""added waze_alerts and waze_traffic_jams tables

Revision ID: 7d4af180fcf6
Revises: 7574885e1fed
Create Date: 2020-02-29 13:38:31.630886

"""

# revision identifiers, used by Alembic.
revision = '7d4af180fcf6'
down_revision = '7574885e1fed'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waze_alerts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('lontitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('magvar', sa.Integer(), nullable=True),
    sa.Column('number_thumbs_up', sa.Integer(), nullable=True),
    sa.Column('report_rating', sa.Integer(), nullable=True),
    sa.Column('reliability', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.Text(), nullable=True),
    sa.Column('alert_subtype', sa.Text(), nullable=True),
    sa.Column('uuid', sa.Text(), nullable=True),
    sa.Column('street', sa.Text(), nullable=True),
    sa.Column('road_type', sa.Integer(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waze_alerts_created_at'), 'waze_alerts', ['created_at'], unique=False)
    op.create_table('waze_trafic_jams',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('line', sa.Text(), nullable=True),
    sa.Column('speed_kmh', sa.Integer(), nullable=True),
    sa.Column('turn_type', sa.Integer(), nullable=True),
    sa.Column('length', sa.Float(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('uuid', sa.Text(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('segments', sa.Text(), nullable=True),
    sa.Column('road_type', sa.Integer(), nullable=True),
    sa.Column('delay', sa.Integer(), nullable=True),
    sa.Column('street', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('end_node', sa.Text(), nullable=True),
    sa.Column('blocking_alert_uuid', sa.Text(), nullable=True),
    sa.Column('start_node', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waze_trafic_jams_created_at'), 'waze_trafic_jams', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waze_trafic_jams_created_at'), table_name='waze_trafic_jams')
    op.drop_table('waze_trafic_jams')
    op.drop_index(op.f('ix_waze_alerts_created_at'), table_name='waze_alerts')
    op.drop_table('waze_alerts')
    # ### end Alembic commands ###
