"""Add news_flash fields

Revision ID: 7f629b4c8891
Revises: f37cf804eea4
Create Date: 2019-12-28 21:33:33.395313

"""

# revision identifiers, used by Alembic.
revision = '7f629b4c8891'
down_revision = 'f37cf804eea4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    conn.execute("CREATE SEQUENCE news_flash_id_seq;")
    conn.execute("ALTER TABLE news_flash ALTER COLUMN id SET DEFAULT nextval('news_flash_id_seq');")
    conn.execute("ALTER SEQUENCE news_flash_id_seq OWNED BY news_flash.id;")
    conn.execute("SELECT setval('news_flash_id_seq', COALESCE(max(id), 0)) FROM news_flash;")
    op.add_column('news_flash', sa.Column('district_hebrew', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('non_urban_intersection_hebrew', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('region_hebrew', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('road_segment_name', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('street1_hebrew', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('street2_hebrew', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('yishuv_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_flash', 'yishuv_name')
    op.drop_column('news_flash', 'street2_hebrew')
    op.drop_column('news_flash', 'street1_hebrew')
    op.drop_column('news_flash', 'road_segment_name')
    op.drop_column('news_flash', 'region_hebrew')
    op.drop_column('news_flash', 'non_urban_intersection_hebrew')
    op.drop_column('news_flash', 'district_hebrew')
    # ### end Alembic commands ###
