"""removed unusued news_flash fields

Revision ID: 8382cebc727b
Revises: 7f629b4c8891
Create Date: 2020-01-08 00:31:36.117465

"""

# revision identifiers, used by Alembic.
revision = '8382cebc727b'
down_revision = '7f629b4c8891'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_flash', 'street2')
    op.drop_column('news_flash', 'street')
    op.drop_column('news_flash', 'intersection')
    op.drop_column('news_flash', 'geo_extracted_street')
    op.drop_column('news_flash', 'geo_extracted_road_no')
    op.drop_column('news_flash', 'geo_extracted_intersection')
    op.drop_column('news_flash', 'geo_extracted_district')
    op.drop_column('news_flash', 'geo_extracted_city')
    op.drop_column('news_flash', 'geo_extracted_address')
    op.drop_column('news_flash', 'city')
    # ### end Alembic commands ###


def downgrade():
    op.add_column('news_flash', sa.Column('city', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('geo_extracted_address', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('geo_extracted_city', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('geo_extracted_district', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('geo_extracted_intersection', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('geo_extracted_road_no', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('geo_extracted_street', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('intersection', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('street', sa.Text(), nullable=True))
    op.add_column('news_flash', sa.Column('street2', sa.Text(), nullable=True))
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
