"""track telegram messages

Revision ID: 881e7b1dba8a
Revises: 664f8a93794e
Create Date: 2023-11-21 12:39:32.931262

"""

# revision identifiers, used by Alembic.
revision = '881e7b1dba8a'
down_revision = '664f8a93794e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_forwarded_messages',
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('newsflash_id', sa.Integer(), nullable=False),
    sa.Column('group_sent', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_forwarded_messages')
    # ### end Alembic commands ###
