"""added back filled column to waze tables

Revision ID: 9687ef04f99d
Revises: 9cae282981fd
Create Date: 2020-10-20 19:03:15.274733

"""

# revision identifiers, used by Alembic.
revision = '9687ef04f99d'
down_revision = '9cae282981fd'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waze_alerts', sa.Column('back_filled', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_waze_alerts_back_filled'), 'waze_alerts', ['back_filled'], unique=False)
    op.add_column('waze_traffic_jams', sa.Column('back_filled', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_waze_traffic_jams_back_filled'), 'waze_traffic_jams', ['back_filled'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waze_traffic_jams_back_filled'), table_name='waze_traffic_jams')
    op.drop_column('waze_traffic_jams', 'back_filled')
    op.drop_index(op.f('ix_waze_alerts_back_filled'), table_name='waze_alerts')
    op.drop_column('waze_alerts', 'back_filled')
    # ### end Alembic commands ###
