"""Add rsa_license_plate field

Revision ID: 98ad75de45b2
Revises: caae04cdec5c
Create Date: 2020-01-15 03:25:27.864784

"""

# revision identifiers, used by Alembic.
revision = '98ad75de45b2'
down_revision = 'caae04cdec5c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('rsa_license_plate', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markers', 'rsa_license_plate')
    # ### end Alembic commands ###
