"""waze object ended at

Revision ID: 9cae282981fd
Revises: cac481832078
Create Date: 2020-10-20 18:34:54.574378

"""

# revision identifiers, used by Alembic.
revision = '9cae282981fd'
down_revision = 'cac481832078'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waze_alerts', sa.Column('ended_at_estimate', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_waze_alerts_ended_at_estimate'), 'waze_alerts', ['ended_at_estimate'], unique=False)
    op.add_column('waze_traffic_jams', sa.Column('ended_at_estimate', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_waze_traffic_jams_ended_at_estimate'), 'waze_traffic_jams', ['ended_at_estimate'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waze_traffic_jams_ended_at_estimate'), table_name='waze_traffic_jams')
    op.drop_column('waze_traffic_jams', 'ended_at_estimate')
    op.drop_index(op.f('ix_waze_alerts_ended_at_estimate'), table_name='waze_alerts')
    op.drop_column('waze_alerts', 'ended_at_estimate')
    # ### end Alembic commands ###
