"""remove constraint from markers: provider_and_id_idx_markers

Revision ID: 9d24fbb0f1fa
Revises: 3f07363021f6
Create Date: 2019-10-19 21:00:22.609457

"""

# revision identifiers, used by Alembic.
revision = '9d24fbb0f1fa'
down_revision = '3f07363021f6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('provider_and_id_idx_markers', table_name='markers')
    op.create_index('provider_and_id_idx_markers', 'markers', ['provider_and_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('provider_and_id_idx_markers', 'markers', ['provider_and_id'], unique=True)
    # ### end Alembic commands ###
