"""report_problem

Revision ID: c7dd68ed664f
Revises: 131150cfc546
Create Date: 2019-09-16 12:16:04.469627

"""

# revision identifiers, used by Alembic.
revision = 'c7dd68ed664f'
down_revision = '131150cfc546'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_problem',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('problem_description', sa.Text(), nullable=True),
    sa.Column('signs_on_the_road_not_clear', sa.Boolean(), nullable=True),
    sa.Column('signs_problem', sa.Boolean(), nullable=True),
    sa.Column('pothole', sa.Boolean(), nullable=True),
    sa.Column('no_light', sa.Boolean(), nullable=True),
    sa.Column('no_sign', sa.Boolean(), nullable=True),
    sa.Column('crossing_missing', sa.Boolean(), nullable=True),
    sa.Column('sidewalk_is_blocked', sa.Boolean(), nullable=True),
    sa.Column('street_light_issue', sa.Boolean(), nullable=True),
    sa.Column('road_hazard', sa.Boolean(), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('send_to_municipality', sa.Boolean(), nullable=True),
    sa.Column('image_data', sa.String(), nullable=True),
    sa.Column('personal_id', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_problem')
    # ### end Alembic commands ###
