"""removed resolution from comments schema

Revision ID: ca69b2327f42
Revises: 5fd0841324e2
Create Date: 2023-08-17 12:48:23.321600

"""

# revision identifiers, used by Alembic.
revision = 'ca69b2327f42'
down_revision = '5fd0841324e2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###)
    op.drop_index('ix_comments_resolution', table_name='comments')
    op.drop_column('comments', 'resolution')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('resolution', postgresql.ENUM('REGION', 'DISTRICT', 'CITY', 'STREET', 'URBAN_JUNCTION', 'SUBURBAN_ROAD', 'SUBURBAN_JUNCTION', 'OTHER', name='resolutioncategories'), autoincrement=False, nullable=False))
    op.create_index('ix_comments_resolution', 'comments', ['resolution'], unique=False)

    # ### end Alembic commands ###
