"""Add rsa_severity field

Revision ID: caae04cdec5c
Revises: 8382cebc727b
Create Date: 2020-01-15 02:53:36.072028

"""

# revision identifiers, used by Alembic.
revision = 'caae04cdec5c'
down_revision = '8382cebc727b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markers', sa.Column('rsa_severity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markers', 'rsa_severity')
    # ### end Alembic commands ###
