"""waze alert foreign key for newsflash

Revision ID: cac481832078
Revises: e3b76e3753d6
Create Date: 2020-10-20 15:05:22.283575

"""

# revision identifiers, used by Alembic.
revision = 'cac481832078'
down_revision = 'e3b76e3753d6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_flash', sa.Column('waze_alert', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'news_flash', 'waze_alerts', ['waze_alert'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'news_flash', type_='foreignkey')
    op.drop_column('news_flash', 'waze_alert')
    # ### end Alembic commands ###
