"""add_embedded_reports_table

Revision ID: ce386162d9f4
Revises: 7d4af180fcf6
Create Date: 2020-04-05 20:42:37.613661

"""

# revision identifiers, used by Alembic.
revision = 'ce386162d9f4'
down_revision = '7d4af180fcf6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedded_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_name_english', sa.String(), nullable=False),
    sa.Column('report_name_hebrew', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'report_name_english')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('embedded_reports')
    # ### end Alembic commands ###
