"""Added time fields to waze classes

Revision ID: d2dfd0ce5a7e
Revises: ef627578319a
Create Date: 2021-09-14 20:50:29.009703

"""

# revision identifiers, used by Alembic.
revision = 'd2dfd0ce5a7e'
down_revision = 'ef627578319a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waze_alerts', sa.Column('insertion_time', sa.DateTime(), nullable=True))
    op.add_column('waze_alerts', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_waze_alerts_insertion_time'), 'waze_alerts', ['insertion_time'], unique=False)
    op.create_index(op.f('ix_waze_alerts_update_time'), 'waze_alerts', ['update_time'], unique=False)
    op.drop_index('ix_waze_alerts_uuid', table_name='waze_alerts')
    op.create_index(op.f('ix_waze_alerts_uuid'), 'waze_alerts', ['uuid'], unique=True)
    op.add_column('waze_traffic_jams', sa.Column('insertion_time', sa.DateTime(), nullable=True))
    op.add_column('waze_traffic_jams', sa.Column('update_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_waze_traffic_jams_insertion_time'), 'waze_traffic_jams', ['insertion_time'], unique=False)
    op.create_index(op.f('ix_waze_traffic_jams_update_time'), 'waze_traffic_jams', ['update_time'], unique=False)
    op.drop_index('ix_waze_traffic_jams_uuid', table_name='waze_traffic_jams')
    op.create_index(op.f('ix_waze_traffic_jams_uuid'), 'waze_traffic_jams', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_waze_traffic_jams_uuid'), table_name='waze_traffic_jams')
    op.create_index('ix_waze_traffic_jams_uuid', 'waze_traffic_jams', ['uuid'], unique=False)
    op.drop_index(op.f('ix_waze_traffic_jams_update_time'), table_name='waze_traffic_jams')
    op.drop_index(op.f('ix_waze_traffic_jams_insertion_time'), table_name='waze_traffic_jams')
    op.drop_column('waze_traffic_jams', 'update_time')
    op.drop_column('waze_traffic_jams', 'insertion_time')
    op.drop_index(op.f('ix_waze_alerts_uuid'), table_name='waze_alerts')
    op.create_index('ix_waze_alerts_uuid', 'waze_alerts', ['uuid'], unique=False)
    op.drop_index(op.f('ix_waze_alerts_update_time'), table_name='waze_alerts')
    op.drop_index(op.f('ix_waze_alerts_insertion_time'), table_name='waze_alerts')
    op.drop_column('waze_alerts', 'update_time')
    op.drop_column('waze_alerts', 'insertion_time')
    # ### end Alembic commands ###
