"""added tags column to news_flash

Revision ID: d9d44c748c7e
Revises: 7d4af180fcf6
Create Date: 2020-03-16 13:26:10.480671

"""

# revision identifiers, used by Alembic.
revision = 'd9d44c748c7e'
down_revision = '7d4af180fcf6'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_flash', sa.Column('tags', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_flash', 'tags')
    # ### end Alembic commands ###
