"""Add tweet_id to news_flash

Revision ID: f37cf804eea4
Revises: a963cf0d6843
Create Date: 2019-12-14 19:12:46.280735

"""

# revision identifiers, used by Alembic.
revision = 'f37cf804eea4'
down_revision = 'a963cf0d6843'
branch_labels = None
depends_on = None

import sqlalchemy as sa

from alembic import op


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_flash', sa.Column('tweet_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_flash', 'tweet_id')
    # ### end Alembic commands ###
