"""add house number

Revision ID: mn9px8cacn24
Revises: 53d0b00fb750
Create Date: 2024-06-16 15:05:30.522542

"""

# revision identifiers, used by Alembic.
revision = 'mn9px8cacn24'
down_revision = '53d0b00fb750'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('involved_markers_hebrew', sa.Column('house_number', sa.Integer(), nullable=True))
    op.add_column('vehicles_markers_hebrew', sa.Column('house_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles_markers_hebrew', 'house_number')
    op.drop_column('involved_markers_hebrew', 'house_number')
    # ### end Alembic commands ###